# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.10
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.



from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_apogeeUSB', [dirname(__file__)])
        except ImportError:
            import _apogeeUSB
            return _apogeeUSB
        if fp is not None:
            try:
                _mod = imp.load_module('_apogeeUSB', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _apogeeUSB = swig_import_helper()
    del swig_import_helper
else:
    import _apogeeUSB
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


MAX_INTEL_HEX_RECORD_LENGTH = _apogeeUSB.MAX_INTEL_HEX_RECORD_LENGTH
class INTEL_HEX_RECORD(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, INTEL_HEX_RECORD, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, INTEL_HEX_RECORD, name)
    __repr__ = _swig_repr
    __swig_setmethods__["Length"] = _apogeeUSB.INTEL_HEX_RECORD_Length_set
    __swig_getmethods__["Length"] = _apogeeUSB.INTEL_HEX_RECORD_Length_get
    if _newclass:Length = _swig_property(_apogeeUSB.INTEL_HEX_RECORD_Length_get, _apogeeUSB.INTEL_HEX_RECORD_Length_set)
    __swig_setmethods__["Address"] = _apogeeUSB.INTEL_HEX_RECORD_Address_set
    __swig_getmethods__["Address"] = _apogeeUSB.INTEL_HEX_RECORD_Address_get
    if _newclass:Address = _swig_property(_apogeeUSB.INTEL_HEX_RECORD_Address_get, _apogeeUSB.INTEL_HEX_RECORD_Address_set)
    __swig_setmethods__["Type"] = _apogeeUSB.INTEL_HEX_RECORD_Type_set
    __swig_getmethods__["Type"] = _apogeeUSB.INTEL_HEX_RECORD_Type_get
    if _newclass:Type = _swig_property(_apogeeUSB.INTEL_HEX_RECORD_Type_get, _apogeeUSB.INTEL_HEX_RECORD_Type_set)
    __swig_setmethods__["Data"] = _apogeeUSB.INTEL_HEX_RECORD_Data_set
    __swig_getmethods__["Data"] = _apogeeUSB.INTEL_HEX_RECORD_Data_get
    if _newclass:Data = _swig_property(_apogeeUSB.INTEL_HEX_RECORD_Data_get, _apogeeUSB.INTEL_HEX_RECORD_Data_set)
    def __init__(self): 
        this = _apogeeUSB.new_INTEL_HEX_RECORD()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _apogeeUSB.delete_INTEL_HEX_RECORD
    __del__ = lambda self : None;
INTEL_HEX_RECORD_swigregister = _apogeeUSB.INTEL_HEX_RECORD_swigregister
INTEL_HEX_RECORD_swigregister(INTEL_HEX_RECORD)

CAPNCAMERA_SUCCESS = _apogeeUSB.CAPNCAMERA_SUCCESS
CAPNCAMERA_ERR_CONNECT = _apogeeUSB.CAPNCAMERA_ERR_CONNECT
CAPNCAMERA_ERR_READ = _apogeeUSB.CAPNCAMERA_ERR_READ
CAPNCAMERA_ERR_WRITE = _apogeeUSB.CAPNCAMERA_ERR_WRITE
CAPNCAMERA_ERR_IMAGE = _apogeeUSB.CAPNCAMERA_ERR_IMAGE
CAPNCAMERA_ERR_LINE = _apogeeUSB.CAPNCAMERA_ERR_LINE
CAPNCAMERA_ERR_START_EXP = _apogeeUSB.CAPNCAMERA_ERR_START_EXP
CAPNCAMERA_ERR_STOP_EXP = _apogeeUSB.CAPNCAMERA_ERR_STOP_EXP
CAPNCAMERA_ERR_QUERY = _apogeeUSB.CAPNCAMERA_ERR_QUERY
CAPNCAMERA_ERR_SN = _apogeeUSB.CAPNCAMERA_ERR_SN
class FEATURE_SUPPORT_LIST(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, FEATURE_SUPPORT_LIST, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, FEATURE_SUPPORT_LIST, name)
    __repr__ = _swig_repr
    __swig_setmethods__["bSequenceBulkDownload"] = _apogeeUSB.FEATURE_SUPPORT_LIST_bSequenceBulkDownload_set
    __swig_getmethods__["bSequenceBulkDownload"] = _apogeeUSB.FEATURE_SUPPORT_LIST_bSequenceBulkDownload_get
    if _newclass:bSequenceBulkDownload = _swig_property(_apogeeUSB.FEATURE_SUPPORT_LIST_bSequenceBulkDownload_get, _apogeeUSB.FEATURE_SUPPORT_LIST_bSequenceBulkDownload_set)
    def __init__(self): 
        this = _apogeeUSB.new_FEATURE_SUPPORT_LIST()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _apogeeUSB.delete_FEATURE_SUPPORT_LIST
    __del__ = lambda self : None;
FEATURE_SUPPORT_LIST_swigregister = _apogeeUSB.FEATURE_SUPPORT_LIST_swigregister
FEATURE_SUPPORT_LIST_swigregister(FEATURE_SUPPORT_LIST)

class CApnCamera(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, CApnCamera, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, CApnCamera, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _apogeeUSB.new_CApnCamera()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _apogeeUSB.delete_CApnCamera
    __del__ = lambda self : None;
    def GetDeviceHandle(self, *args): return _apogeeUSB.CApnCamera_GetDeviceHandle(self, *args)
    def InitDriver(self, *args): return _apogeeUSB.CApnCamera_InitDriver(self, *args)
    def SimpleInitDriver(self, *args): return _apogeeUSB.CApnCamera_SimpleInitDriver(self, *args)
    def GetCameraInterface(self): return _apogeeUSB.CApnCamera_GetCameraInterface(self)
    def GetCameraSerialNumber(self, *args): return _apogeeUSB.CApnCamera_GetCameraSerialNumber(self, *args)
    def GetSystemDriverVersion(self, *args): return _apogeeUSB.CApnCamera_GetSystemDriverVersion(self, *args)
    def GetUsb8051FirmwareRev(self, *args): return _apogeeUSB.CApnCamera_GetUsb8051FirmwareRev(self, *args)
    def GetUsbProductId(self, *args): return _apogeeUSB.CApnCamera_GetUsbProductId(self, *args)
    def GetUsbDeviceId(self, *args): return _apogeeUSB.CApnCamera_GetUsbDeviceId(self, *args)
    def CloseDriver(self): return _apogeeUSB.CApnCamera_CloseDriver(self)
    def PreStartExpose(self, *args): return _apogeeUSB.CApnCamera_PreStartExpose(self, *args)
    def PostStopExposure(self, *args): return _apogeeUSB.CApnCamera_PostStopExposure(self, *args)
    def GetImageData(self, *args): return _apogeeUSB.CApnCamera_GetImageData(self, *args)
    def GetLineData(self, *args): return _apogeeUSB.CApnCamera_GetLineData(self, *args)
    def Read(self, *args): return _apogeeUSB.CApnCamera_Read(self, *args)
    def Write(self, *args): return _apogeeUSB.CApnCamera_Write(self, *args)
    def WriteMultiSRMD(self, *args): return _apogeeUSB.CApnCamera_WriteMultiSRMD(self, *args)
    def WriteMultiMRMD(self, *args): return _apogeeUSB.CApnCamera_WriteMultiMRMD(self, *args)
    def QueryStatusRegs(self, *args): return _apogeeUSB.CApnCamera_QueryStatusRegs(self, *args)
    def SetNetworkTransferMode(self, *args): return _apogeeUSB.CApnCamera_SetNetworkTransferMode(self, *args)
    def SetCameraSerialNumber(self, *args): return _apogeeUSB.CApnCamera_SetCameraSerialNumber(self, *args)
    def DownloadFirmware(self, *args): return _apogeeUSB.CApnCamera_DownloadFirmware(self, *args)
    def InitDefaults(self): return _apogeeUSB.CApnCamera_InitDefaults(self)
    def Expose(self, *args): return _apogeeUSB.CApnCamera_Expose(self, *args)
    def GetImage(self, *args): return _apogeeUSB.CApnCamera_GetImage(self, *args)
    def BufferImage(self, *args): return _apogeeUSB.CApnCamera_BufferImage(self, *args)
    def BufferDriftScan(self, *args): return _apogeeUSB.CApnCamera_BufferDriftScan(self, *args)
    def StopExposure(self, *args): return _apogeeUSB.CApnCamera_StopExposure(self, *args)
    def PowerDown(self): return _apogeeUSB.CApnCamera_PowerDown(self)
    def Resume(self): return _apogeeUSB.CApnCamera_Resume(self)
    def ResetSystem(self): return _apogeeUSB.CApnCamera_ResetSystem(self)
    def ResetSystemNoFlush(self): return _apogeeUSB.CApnCamera_ResetSystemNoFlush(self)
    def PauseTimer(self, *args): return _apogeeUSB.CApnCamera_PauseTimer(self, *args)
    def GuideAbort(self): return _apogeeUSB.CApnCamera_GuideAbort(self)
    def GuideRAPlus(self): return _apogeeUSB.CApnCamera_GuideRAPlus(self)
    def GuideRAMinus(self): return _apogeeUSB.CApnCamera_GuideRAMinus(self)
    def GuideDecPlus(self): return _apogeeUSB.CApnCamera_GuideDecPlus(self)
    def GuideDecMinus(self): return _apogeeUSB.CApnCamera_GuideDecMinus(self)
    def ConvertBayerImageToRGB(self, *args): return _apogeeUSB.CApnCamera_ConvertBayerImageToRGB(self, *args)
    def ImageReady(self): return _apogeeUSB.CApnCamera_ImageReady(self)
    def ImageInProgress(self): return _apogeeUSB.CApnCamera_ImageInProgress(self)
    def SignalImagingDone(self): return _apogeeUSB.CApnCamera_SignalImagingDone(self)
    def GetExposurePixelsH(self): return _apogeeUSB.CApnCamera_GetExposurePixelsH(self)
    def GetExposurePixelsV(self): return _apogeeUSB.CApnCamera_GetExposurePixelsV(self)
    def read_Present(self): return _apogeeUSB.CApnCamera_read_Present(self)
    def read_FirmwareVersion(self): return _apogeeUSB.CApnCamera_read_FirmwareVersion(self)
    def read_CameraModel(self, *args): return _apogeeUSB.CApnCamera_read_CameraModel(self, *args)
    def read_ShutterState(self): return _apogeeUSB.CApnCamera_read_ShutterState(self)
    def read_DisableShutter(self): return _apogeeUSB.CApnCamera_read_DisableShutter(self)
    def write_DisableShutter(self, *args): return _apogeeUSB.CApnCamera_write_DisableShutter(self, *args)
    def read_ForceShutterOpen(self): return _apogeeUSB.CApnCamera_read_ForceShutterOpen(self)
    def write_ForceShutterOpen(self, *args): return _apogeeUSB.CApnCamera_write_ForceShutterOpen(self, *args)
    def read_ShutterAmpControl(self): return _apogeeUSB.CApnCamera_read_ShutterAmpControl(self)
    def write_ShutterAmpControl(self, *args): return _apogeeUSB.CApnCamera_write_ShutterAmpControl(self, *args)
    def read_DisableFlushCommands(self): return _apogeeUSB.CApnCamera_read_DisableFlushCommands(self)
    def write_DisableFlushCommands(self, *args): return _apogeeUSB.CApnCamera_write_DisableFlushCommands(self, *args)
    def read_DisablePostExposeFlushing(self): return _apogeeUSB.CApnCamera_read_DisablePostExposeFlushing(self)
    def write_DisablePostExposeFlushing(self, *args): return _apogeeUSB.CApnCamera_write_DisablePostExposeFlushing(self, *args)
    def read_ExternalIoReadout(self): return _apogeeUSB.CApnCamera_read_ExternalIoReadout(self)
    def write_ExternalIoReadout(self, *args): return _apogeeUSB.CApnCamera_write_ExternalIoReadout(self, *args)
    def read_ExternalShutter(self): return _apogeeUSB.CApnCamera_read_ExternalShutter(self)
    def write_ExternalShutter(self, *args): return _apogeeUSB.CApnCamera_write_ExternalShutter(self, *args)
    def read_FastSequence(self): return _apogeeUSB.CApnCamera_read_FastSequence(self)
    def write_FastSequence(self, *args): return _apogeeUSB.CApnCamera_write_FastSequence(self, *args)
    def read_CameraMode(self): return _apogeeUSB.CApnCamera_read_CameraMode(self)
    def write_CameraMode(self, *args): return _apogeeUSB.CApnCamera_write_CameraMode(self, *args)
    def read_DataBits(self): return _apogeeUSB.CApnCamera_read_DataBits(self)
    def write_DataBits(self, *args): return _apogeeUSB.CApnCamera_write_DataBits(self, *args)
    def read_ImagingStatus(self): return _apogeeUSB.CApnCamera_read_ImagingStatus(self)
    def read_LedMode(self): return _apogeeUSB.CApnCamera_read_LedMode(self)
    def write_LedMode(self, *args): return _apogeeUSB.CApnCamera_write_LedMode(self, *args)
    def read_LedState(self, *args): return _apogeeUSB.CApnCamera_read_LedState(self, *args)
    def write_LedState(self, *args): return _apogeeUSB.CApnCamera_write_LedState(self, *args)
    def read_CoolerEnable(self): return _apogeeUSB.CApnCamera_read_CoolerEnable(self)
    def write_CoolerEnable(self, *args): return _apogeeUSB.CApnCamera_write_CoolerEnable(self, *args)
    def read_CoolerStatus(self): return _apogeeUSB.CApnCamera_read_CoolerStatus(self)
    def read_CoolerSetPoint(self): return _apogeeUSB.CApnCamera_read_CoolerSetPoint(self)
    def write_CoolerSetPoint(self, *args): return _apogeeUSB.CApnCamera_write_CoolerSetPoint(self, *args)
    def read_CoolerBackoffPoint(self): return _apogeeUSB.CApnCamera_read_CoolerBackoffPoint(self)
    def write_CoolerBackoffPoint(self, *args): return _apogeeUSB.CApnCamera_write_CoolerBackoffPoint(self, *args)
    def read_CoolerDrive(self): return _apogeeUSB.CApnCamera_read_CoolerDrive(self)
    def read_TempCCD(self): return _apogeeUSB.CApnCamera_read_TempCCD(self)
    def read_TempHeatsink(self): return _apogeeUSB.CApnCamera_read_TempHeatsink(self)
    def read_FanMode(self): return _apogeeUSB.CApnCamera_read_FanMode(self)
    def write_FanMode(self, *args): return _apogeeUSB.CApnCamera_write_FanMode(self, *args)
    def write_FlushBinningV(self, *args): return _apogeeUSB.CApnCamera_write_FlushBinningV(self, *args)
    def read_FlushBinningV(self): return _apogeeUSB.CApnCamera_read_FlushBinningV(self)
    def read_MaxBinningH(self): return _apogeeUSB.CApnCamera_read_MaxBinningH(self)
    def read_MaxBinningV(self): return _apogeeUSB.CApnCamera_read_MaxBinningV(self)
    def write_RoiBinningH(self, *args): return _apogeeUSB.CApnCamera_write_RoiBinningH(self, *args)
    def read_RoiBinningH(self): return _apogeeUSB.CApnCamera_read_RoiBinningH(self)
    def write_RoiBinningV(self, *args): return _apogeeUSB.CApnCamera_write_RoiBinningV(self, *args)
    def read_RoiBinningV(self): return _apogeeUSB.CApnCamera_read_RoiBinningV(self)
    def read_RoiPixelsH(self): return _apogeeUSB.CApnCamera_read_RoiPixelsH(self)
    def write_RoiPixelsH(self, *args): return _apogeeUSB.CApnCamera_write_RoiPixelsH(self, *args)
    def read_RoiPixelsV(self): return _apogeeUSB.CApnCamera_read_RoiPixelsV(self)
    def write_RoiPixelsV(self, *args): return _apogeeUSB.CApnCamera_write_RoiPixelsV(self, *args)
    def read_RoiStartX(self): return _apogeeUSB.CApnCamera_read_RoiStartX(self)
    def write_RoiStartX(self, *args): return _apogeeUSB.CApnCamera_write_RoiStartX(self, *args)
    def read_RoiStartY(self): return _apogeeUSB.CApnCamera_read_RoiStartY(self)
    def write_RoiStartY(self, *args): return _apogeeUSB.CApnCamera_write_RoiStartY(self, *args)
    def read_DigitizeOverscan(self): return _apogeeUSB.CApnCamera_read_DigitizeOverscan(self)
    def write_DigitizeOverscan(self, *args): return _apogeeUSB.CApnCamera_write_DigitizeOverscan(self, *args)
    def read_OverscanColumns(self): return _apogeeUSB.CApnCamera_read_OverscanColumns(self)
    def read_ShutterStrobePosition(self): return _apogeeUSB.CApnCamera_read_ShutterStrobePosition(self)
    def write_ShutterStrobePosition(self, *args): return _apogeeUSB.CApnCamera_write_ShutterStrobePosition(self, *args)
    def read_ShutterStrobePeriod(self): return _apogeeUSB.CApnCamera_read_ShutterStrobePeriod(self)
    def write_ShutterStrobePeriod(self, *args): return _apogeeUSB.CApnCamera_write_ShutterStrobePeriod(self, *args)
    def read_ShutterCloseDelay(self): return _apogeeUSB.CApnCamera_read_ShutterCloseDelay(self)
    def write_ShutterCloseDelay(self, *args): return _apogeeUSB.CApnCamera_write_ShutterCloseDelay(self, *args)
    def read_SequenceBulkDownload(self): return _apogeeUSB.CApnCamera_read_SequenceBulkDownload(self)
    def write_SequenceBulkDownload(self, *args): return _apogeeUSB.CApnCamera_write_SequenceBulkDownload(self, *args)
    def read_SequenceDelay(self): return _apogeeUSB.CApnCamera_read_SequenceDelay(self)
    def write_SequenceDelay(self, *args): return _apogeeUSB.CApnCamera_write_SequenceDelay(self, *args)
    def read_VariableSequenceDelay(self): return _apogeeUSB.CApnCamera_read_VariableSequenceDelay(self)
    def write_VariableSequenceDelay(self, *args): return _apogeeUSB.CApnCamera_write_VariableSequenceDelay(self, *args)
    def read_ImageCount(self): return _apogeeUSB.CApnCamera_read_ImageCount(self)
    def write_ImageCount(self, *args): return _apogeeUSB.CApnCamera_write_ImageCount(self, *args)
    def read_SequenceCounter(self): return _apogeeUSB.CApnCamera_read_SequenceCounter(self)
    def read_ExposureImageCount(self): return _apogeeUSB.CApnCamera_read_ExposureImageCount(self)
    def read_ExposureBulkDownload(self): return _apogeeUSB.CApnCamera_read_ExposureBulkDownload(self)
    def read_ContinuousImaging(self): return _apogeeUSB.CApnCamera_read_ContinuousImaging(self)
    def write_ContinuousImaging(self, *args): return _apogeeUSB.CApnCamera_write_ContinuousImaging(self, *args)
    def read_TDICounter(self): return _apogeeUSB.CApnCamera_read_TDICounter(self)
    def read_TDIRows(self): return _apogeeUSB.CApnCamera_read_TDIRows(self)
    def write_TDIRows(self, *args): return _apogeeUSB.CApnCamera_write_TDIRows(self, *args)
    def read_TDIRate(self): return _apogeeUSB.CApnCamera_read_TDIRate(self)
    def write_TDIRate(self, *args): return _apogeeUSB.CApnCamera_write_TDIRate(self, *args)
    def read_TDIBinningV(self): return _apogeeUSB.CApnCamera_read_TDIBinningV(self)
    def write_TDIBinningV(self, *args): return _apogeeUSB.CApnCamera_write_TDIBinningV(self, *args)
    def read_KineticsSections(self): return _apogeeUSB.CApnCamera_read_KineticsSections(self)
    def write_KineticsSections(self, *args): return _apogeeUSB.CApnCamera_write_KineticsSections(self, *args)
    def read_KineticsShiftInterval(self): return _apogeeUSB.CApnCamera_read_KineticsShiftInterval(self)
    def write_KineticsShiftInterval(self, *args): return _apogeeUSB.CApnCamera_write_KineticsShiftInterval(self, *args)
    def read_KineticsSectionHeight(self): return _apogeeUSB.CApnCamera_read_KineticsSectionHeight(self)
    def write_KineticsSectionHeight(self, *args): return _apogeeUSB.CApnCamera_write_KineticsSectionHeight(self, *args)
    def read_TriggerNormalEach(self): return _apogeeUSB.CApnCamera_read_TriggerNormalEach(self)
    def write_TriggerNormalEach(self, *args): return _apogeeUSB.CApnCamera_write_TriggerNormalEach(self, *args)
    def read_TriggerNormalGroup(self): return _apogeeUSB.CApnCamera_read_TriggerNormalGroup(self)
    def write_TriggerNormalGroup(self, *args): return _apogeeUSB.CApnCamera_write_TriggerNormalGroup(self, *args)
    def read_TriggerTdiKineticsEach(self): return _apogeeUSB.CApnCamera_read_TriggerTdiKineticsEach(self)
    def write_TriggerTdiKineticsEach(self, *args): return _apogeeUSB.CApnCamera_write_TriggerTdiKineticsEach(self, *args)
    def read_TriggerTdiKineticsGroup(self): return _apogeeUSB.CApnCamera_read_TriggerTdiKineticsGroup(self)
    def write_TriggerTdiKineticsGroup(self, *args): return _apogeeUSB.CApnCamera_write_TriggerTdiKineticsGroup(self, *args)
    def read_ExposureTriggerEach(self): return _apogeeUSB.CApnCamera_read_ExposureTriggerEach(self)
    def read_ExposureTriggerGroup(self): return _apogeeUSB.CApnCamera_read_ExposureTriggerGroup(self)
    def read_ExposureExternalShutter(self): return _apogeeUSB.CApnCamera_read_ExposureExternalShutter(self)
    def read_PreFlashEnable(self): return _apogeeUSB.CApnCamera_read_PreFlashEnable(self)
    def write_PreFlashEnable(self, *args): return _apogeeUSB.CApnCamera_write_PreFlashEnable(self, *args)
    def read_IoPortAssignment(self): return _apogeeUSB.CApnCamera_read_IoPortAssignment(self)
    def write_IoPortAssignment(self, *args): return _apogeeUSB.CApnCamera_write_IoPortAssignment(self, *args)
    def read_IoPortBlankingBits(self): return _apogeeUSB.CApnCamera_read_IoPortBlankingBits(self)
    def write_IoPortBlankingBits(self, *args): return _apogeeUSB.CApnCamera_write_IoPortBlankingBits(self, *args)
    def read_IoPortDirection(self): return _apogeeUSB.CApnCamera_read_IoPortDirection(self)
    def write_IoPortDirection(self, *args): return _apogeeUSB.CApnCamera_write_IoPortDirection(self, *args)
    def read_IoPortData(self): return _apogeeUSB.CApnCamera_read_IoPortData(self)
    def write_IoPortData(self, *args): return _apogeeUSB.CApnCamera_write_IoPortData(self, *args)
    def read_TwelveBitGain(self): return _apogeeUSB.CApnCamera_read_TwelveBitGain(self)
    def write_TwelveBitGain(self, *args): return _apogeeUSB.CApnCamera_write_TwelveBitGain(self, *args)
    def read_TwelveBitOffset(self): return _apogeeUSB.CApnCamera_read_TwelveBitOffset(self)
    def write_TwelveBitOffset(self, *args): return _apogeeUSB.CApnCamera_write_TwelveBitOffset(self, *args)
    def read_InputVoltage(self): return _apogeeUSB.CApnCamera_read_InputVoltage(self)
    def read_AvailableMemory(self): return _apogeeUSB.CApnCamera_read_AvailableMemory(self)
    def read_MaxExposureTime(self): return _apogeeUSB.CApnCamera_read_MaxExposureTime(self)
    def read_NetworkTransferMode(self): return _apogeeUSB.CApnCamera_read_NetworkTransferMode(self)
    def write_NetworkTransferMode(self, *args): return _apogeeUSB.CApnCamera_write_NetworkTransferMode(self, *args)
    def read_TestLedBrightness(self): return _apogeeUSB.CApnCamera_read_TestLedBrightness(self)
    def write_TestLedBrightness(self, *args): return _apogeeUSB.CApnCamera_write_TestLedBrightness(self, *args)
    def read_PlatformType(self): return _apogeeUSB.CApnCamera_read_PlatformType(self)
    def read_AscentADGainSixteenLeft(self): return _apogeeUSB.CApnCamera_read_AscentADGainSixteenLeft(self)
    def read_AscentADGainSixteenRight(self): return _apogeeUSB.CApnCamera_read_AscentADGainSixteenRight(self)
    def write_AscentADGainSixteen(self, *args): return _apogeeUSB.CApnCamera_write_AscentADGainSixteen(self, *args)
    def read_AscentADOffsetSixteenLeft(self): return _apogeeUSB.CApnCamera_read_AscentADOffsetSixteenLeft(self)
    def read_AscentADOffsetSixteenRight(self): return _apogeeUSB.CApnCamera_read_AscentADOffsetSixteenRight(self)
    def write_AscentADOffsetSixteen(self, *args): return _apogeeUSB.CApnCamera_write_AscentADOffsetSixteen(self, *args)
    def read_DigitizationSpeed(self): return _apogeeUSB.CApnCamera_read_DigitizationSpeed(self)
    def write_DigitizationSpeed(self, *args): return _apogeeUSB.CApnCamera_write_DigitizationSpeed(self, *args)
    def read_DataAveraging(self): return _apogeeUSB.CApnCamera_read_DataAveraging(self)
    def write_DataAveraging(self, *args): return _apogeeUSB.CApnCamera_write_DataAveraging(self, *args)
    def read_DualReadout(self): return _apogeeUSB.CApnCamera_read_DualReadout(self)
    def write_DualReadout(self, *args): return _apogeeUSB.CApnCamera_write_DualReadout(self, *args)
    def read_ConnectionTest(self): return _apogeeUSB.CApnCamera_read_ConnectionTest(self)
    def read_GuideActive(self): return _apogeeUSB.CApnCamera_read_GuideActive(self)
    def read_GuideRAPlusDuration(self): return _apogeeUSB.CApnCamera_read_GuideRAPlusDuration(self)
    def write_GuideRAPlusDuration(self, *args): return _apogeeUSB.CApnCamera_write_GuideRAPlusDuration(self, *args)
    def read_GuideRAMinusDuration(self): return _apogeeUSB.CApnCamera_read_GuideRAMinusDuration(self)
    def write_GuideRAMinusDuration(self, *args): return _apogeeUSB.CApnCamera_write_GuideRAMinusDuration(self, *args)
    def read_GuideDecPlusDuration(self): return _apogeeUSB.CApnCamera_read_GuideDecPlusDuration(self)
    def write_GuideDecPlusDuration(self, *args): return _apogeeUSB.CApnCamera_write_GuideDecPlusDuration(self, *args)
    def read_GuideDecMinusDuration(self): return _apogeeUSB.CApnCamera_read_GuideDecMinusDuration(self)
    def write_GuideDecMinusDuration(self, *args): return _apogeeUSB.CApnCamera_write_GuideDecMinusDuration(self, *args)
    def read_BayerStartPosition(self): return _apogeeUSB.CApnCamera_read_BayerStartPosition(self)
    def write_BayerStartPosition(self, *args): return _apogeeUSB.CApnCamera_write_BayerStartPosition(self, *args)
    __swig_setmethods__["m_ApnSensorInfo"] = _apogeeUSB.CApnCamera_m_ApnSensorInfo_set
    __swig_getmethods__["m_ApnSensorInfo"] = _apogeeUSB.CApnCamera_m_ApnSensorInfo_get
    if _newclass:m_ApnSensorInfo = _swig_property(_apogeeUSB.CApnCamera_m_ApnSensorInfo_get, _apogeeUSB.CApnCamera_m_ApnSensorInfo_set)
    def LoadVerticalPattern(self): return _apogeeUSB.CApnCamera_LoadVerticalPattern(self)
    def LoadClampPattern(self, *args): return _apogeeUSB.CApnCamera_LoadClampPattern(self, *args)
    def LoadSkipPattern(self, *args): return _apogeeUSB.CApnCamera_LoadSkipPattern(self, *args)
    def LoadRoiPattern(self, *args): return _apogeeUSB.CApnCamera_LoadRoiPattern(self, *args)
    def WriteHorizontalPattern(self, *args): return _apogeeUSB.CApnCamera_WriteHorizontalPattern(self, *args)
    def InitTwelveBitAD(self): return _apogeeUSB.CApnCamera_InitTwelveBitAD(self)
    def InitAscentSixteenBitAD(self): return _apogeeUSB.CApnCamera_InitAscentSixteenBitAD(self)
    def UpdateGeneralStatus(self): return _apogeeUSB.CApnCamera_UpdateGeneralStatus(self)
    def LookupAltaCameraId(self, *args): return _apogeeUSB.CApnCamera_LookupAltaCameraId(self, *args)
    def LookupAscentCameraId(self, *args): return _apogeeUSB.CApnCamera_LookupAscentCameraId(self, *args)
    def CheckGuiderRelayDuration(self, *args): return _apogeeUSB.CApnCamera_CheckGuiderRelayDuration(self, *args)
    def CalculateGuiderRelayTimeCounts(self, *args): return _apogeeUSB.CApnCamera_CalculateGuiderRelayTimeCounts(self, *args)
    def IssueExposeCommand(self, *args): return _apogeeUSB.CApnCamera_IssueExposeCommand(self, *args)
    def TakeNoDataDarkExposure(self, *args): return _apogeeUSB.CApnCamera_TakeNoDataDarkExposure(self, *args)
    def PostExposureRestoreParams(self): return _apogeeUSB.CApnCamera_PostExposureRestoreParams(self)
    __swig_setmethods__["m_pvtPlatformType"] = _apogeeUSB.CApnCamera_m_pvtPlatformType_set
    __swig_getmethods__["m_pvtPlatformType"] = _apogeeUSB.CApnCamera_m_pvtPlatformType_get
    if _newclass:m_pvtPlatformType = _swig_property(_apogeeUSB.CApnCamera_m_pvtPlatformType_get, _apogeeUSB.CApnCamera_m_pvtPlatformType_set)
    __swig_setmethods__["m_pvtResetVerticalArrays"] = _apogeeUSB.CApnCamera_m_pvtResetVerticalArrays_set
    __swig_getmethods__["m_pvtResetVerticalArrays"] = _apogeeUSB.CApnCamera_m_pvtResetVerticalArrays_get
    if _newclass:m_pvtResetVerticalArrays = _swig_property(_apogeeUSB.CApnCamera_m_pvtResetVerticalArrays_get, _apogeeUSB.CApnCamera_m_pvtResetVerticalArrays_set)
    __swig_setmethods__["m_pvtNewFeatureSupport"] = _apogeeUSB.CApnCamera_m_pvtNewFeatureSupport_set
    __swig_getmethods__["m_pvtNewFeatureSupport"] = _apogeeUSB.CApnCamera_m_pvtNewFeatureSupport_get
    if _newclass:m_pvtNewFeatureSupport = _swig_property(_apogeeUSB.CApnCamera_m_pvtNewFeatureSupport_get, _apogeeUSB.CApnCamera_m_pvtNewFeatureSupport_set)
    __swig_setmethods__["m_pvtRoiBinningH"] = _apogeeUSB.CApnCamera_m_pvtRoiBinningH_set
    __swig_getmethods__["m_pvtRoiBinningH"] = _apogeeUSB.CApnCamera_m_pvtRoiBinningH_get
    if _newclass:m_pvtRoiBinningH = _swig_property(_apogeeUSB.CApnCamera_m_pvtRoiBinningH_get, _apogeeUSB.CApnCamera_m_pvtRoiBinningH_set)
    __swig_setmethods__["m_pvtRoiBinningV"] = _apogeeUSB.CApnCamera_m_pvtRoiBinningV_set
    __swig_getmethods__["m_pvtRoiBinningV"] = _apogeeUSB.CApnCamera_m_pvtRoiBinningV_get
    if _newclass:m_pvtRoiBinningV = _swig_property(_apogeeUSB.CApnCamera_m_pvtRoiBinningV_get, _apogeeUSB.CApnCamera_m_pvtRoiBinningV_set)
    __swig_setmethods__["m_pvtRoiPixelsH"] = _apogeeUSB.CApnCamera_m_pvtRoiPixelsH_set
    __swig_getmethods__["m_pvtRoiPixelsH"] = _apogeeUSB.CApnCamera_m_pvtRoiPixelsH_get
    if _newclass:m_pvtRoiPixelsH = _swig_property(_apogeeUSB.CApnCamera_m_pvtRoiPixelsH_get, _apogeeUSB.CApnCamera_m_pvtRoiPixelsH_set)
    __swig_setmethods__["m_pvtRoiPixelsV"] = _apogeeUSB.CApnCamera_m_pvtRoiPixelsV_set
    __swig_getmethods__["m_pvtRoiPixelsV"] = _apogeeUSB.CApnCamera_m_pvtRoiPixelsV_get
    if _newclass:m_pvtRoiPixelsV = _swig_property(_apogeeUSB.CApnCamera_m_pvtRoiPixelsV_get, _apogeeUSB.CApnCamera_m_pvtRoiPixelsV_set)
    __swig_setmethods__["m_pvtRoiStartX"] = _apogeeUSB.CApnCamera_m_pvtRoiStartX_set
    __swig_getmethods__["m_pvtRoiStartX"] = _apogeeUSB.CApnCamera_m_pvtRoiStartX_get
    if _newclass:m_pvtRoiStartX = _swig_property(_apogeeUSB.CApnCamera_m_pvtRoiStartX_get, _apogeeUSB.CApnCamera_m_pvtRoiStartX_set)
    __swig_setmethods__["m_pvtRoiStartY"] = _apogeeUSB.CApnCamera_m_pvtRoiStartY_set
    __swig_getmethods__["m_pvtRoiStartY"] = _apogeeUSB.CApnCamera_m_pvtRoiStartY_get
    if _newclass:m_pvtRoiStartY = _swig_property(_apogeeUSB.CApnCamera_m_pvtRoiStartY_get, _apogeeUSB.CApnCamera_m_pvtRoiStartY_set)
    __swig_setmethods__["m_pvtCameraMode"] = _apogeeUSB.CApnCamera_m_pvtCameraMode_set
    __swig_getmethods__["m_pvtCameraMode"] = _apogeeUSB.CApnCamera_m_pvtCameraMode_get
    if _newclass:m_pvtCameraMode = _swig_property(_apogeeUSB.CApnCamera_m_pvtCameraMode_get, _apogeeUSB.CApnCamera_m_pvtCameraMode_set)
    __swig_setmethods__["m_pvtExternalShutter"] = _apogeeUSB.CApnCamera_m_pvtExternalShutter_set
    __swig_getmethods__["m_pvtExternalShutter"] = _apogeeUSB.CApnCamera_m_pvtExternalShutter_get
    if _newclass:m_pvtExternalShutter = _swig_property(_apogeeUSB.CApnCamera_m_pvtExternalShutter_get, _apogeeUSB.CApnCamera_m_pvtExternalShutter_set)
    __swig_setmethods__["m_pvtCameraPoweredDown"] = _apogeeUSB.CApnCamera_m_pvtCameraPoweredDown_set
    __swig_getmethods__["m_pvtCameraPoweredDown"] = _apogeeUSB.CApnCamera_m_pvtCameraPoweredDown_get
    if _newclass:m_pvtCameraPoweredDown = _swig_property(_apogeeUSB.CApnCamera_m_pvtCameraPoweredDown_get, _apogeeUSB.CApnCamera_m_pvtCameraPoweredDown_set)
    __swig_setmethods__["m_pvtPowerDownCoolerEnable"] = _apogeeUSB.CApnCamera_m_pvtPowerDownCoolerEnable_set
    __swig_getmethods__["m_pvtPowerDownCoolerEnable"] = _apogeeUSB.CApnCamera_m_pvtPowerDownCoolerEnable_get
    if _newclass:m_pvtPowerDownCoolerEnable = _swig_property(_apogeeUSB.CApnCamera_m_pvtPowerDownCoolerEnable_get, _apogeeUSB.CApnCamera_m_pvtPowerDownCoolerEnable_set)
    __swig_setmethods__["m_pvtPowerDownFanMode"] = _apogeeUSB.CApnCamera_m_pvtPowerDownFanMode_set
    __swig_getmethods__["m_pvtPowerDownFanMode"] = _apogeeUSB.CApnCamera_m_pvtPowerDownFanMode_get
    if _newclass:m_pvtPowerDownFanMode = _swig_property(_apogeeUSB.CApnCamera_m_pvtPowerDownFanMode_get, _apogeeUSB.CApnCamera_m_pvtPowerDownFanMode_set)
    __swig_setmethods__["m_pvtDataBits"] = _apogeeUSB.CApnCamera_m_pvtDataBits_set
    __swig_getmethods__["m_pvtDataBits"] = _apogeeUSB.CApnCamera_m_pvtDataBits_get
    if _newclass:m_pvtDataBits = _swig_property(_apogeeUSB.CApnCamera_m_pvtDataBits_get, _apogeeUSB.CApnCamera_m_pvtDataBits_set)
    __swig_setmethods__["m_pvtNetworkTransferMode"] = _apogeeUSB.CApnCamera_m_pvtNetworkTransferMode_set
    __swig_getmethods__["m_pvtNetworkTransferMode"] = _apogeeUSB.CApnCamera_m_pvtNetworkTransferMode_get
    if _newclass:m_pvtNetworkTransferMode = _swig_property(_apogeeUSB.CApnCamera_m_pvtNetworkTransferMode_get, _apogeeUSB.CApnCamera_m_pvtNetworkTransferMode_set)
    __swig_setmethods__["m_pvtBayerShift"] = _apogeeUSB.CApnCamera_m_pvtBayerShift_set
    __swig_getmethods__["m_pvtBayerShift"] = _apogeeUSB.CApnCamera_m_pvtBayerShift_get
    if _newclass:m_pvtBayerShift = _swig_property(_apogeeUSB.CApnCamera_m_pvtBayerShift_get, _apogeeUSB.CApnCamera_m_pvtBayerShift_set)
    __swig_setmethods__["m_pvtUseAdvancedStatus"] = _apogeeUSB.CApnCamera_m_pvtUseAdvancedStatus_set
    __swig_getmethods__["m_pvtUseAdvancedStatus"] = _apogeeUSB.CApnCamera_m_pvtUseAdvancedStatus_get
    if _newclass:m_pvtUseAdvancedStatus = _swig_property(_apogeeUSB.CApnCamera_m_pvtUseAdvancedStatus_get, _apogeeUSB.CApnCamera_m_pvtUseAdvancedStatus_set)
    __swig_setmethods__["m_pvtCameraID"] = _apogeeUSB.CApnCamera_m_pvtCameraID_set
    __swig_getmethods__["m_pvtCameraID"] = _apogeeUSB.CApnCamera_m_pvtCameraID_get
    if _newclass:m_pvtCameraID = _swig_property(_apogeeUSB.CApnCamera_m_pvtCameraID_get, _apogeeUSB.CApnCamera_m_pvtCameraID_set)
    __swig_setmethods__["m_pvtFirmwareVersion"] = _apogeeUSB.CApnCamera_m_pvtFirmwareVersion_set
    __swig_getmethods__["m_pvtFirmwareVersion"] = _apogeeUSB.CApnCamera_m_pvtFirmwareVersion_get
    if _newclass:m_pvtFirmwareVersion = _swig_property(_apogeeUSB.CApnCamera_m_pvtFirmwareVersion_get, _apogeeUSB.CApnCamera_m_pvtFirmwareVersion_set)
    __swig_setmethods__["m_pvtImageCount"] = _apogeeUSB.CApnCamera_m_pvtImageCount_set
    __swig_getmethods__["m_pvtImageCount"] = _apogeeUSB.CApnCamera_m_pvtImageCount_get
    if _newclass:m_pvtImageCount = _swig_property(_apogeeUSB.CApnCamera_m_pvtImageCount_get, _apogeeUSB.CApnCamera_m_pvtImageCount_set)
    __swig_setmethods__["m_pvtTDIRows"] = _apogeeUSB.CApnCamera_m_pvtTDIRows_set
    __swig_getmethods__["m_pvtTDIRows"] = _apogeeUSB.CApnCamera_m_pvtTDIRows_get
    if _newclass:m_pvtTDIRows = _swig_property(_apogeeUSB.CApnCamera_m_pvtTDIRows_get, _apogeeUSB.CApnCamera_m_pvtTDIRows_set)
    __swig_setmethods__["m_pvtTDIBinningV"] = _apogeeUSB.CApnCamera_m_pvtTDIBinningV_set
    __swig_getmethods__["m_pvtTDIBinningV"] = _apogeeUSB.CApnCamera_m_pvtTDIBinningV_get
    if _newclass:m_pvtTDIBinningV = _swig_property(_apogeeUSB.CApnCamera_m_pvtTDIBinningV_get, _apogeeUSB.CApnCamera_m_pvtTDIBinningV_set)
    __swig_setmethods__["m_pvtTDIRate"] = _apogeeUSB.CApnCamera_m_pvtTDIRate_set
    __swig_getmethods__["m_pvtTDIRate"] = _apogeeUSB.CApnCamera_m_pvtTDIRate_get
    if _newclass:m_pvtTDIRate = _swig_property(_apogeeUSB.CApnCamera_m_pvtTDIRate_get, _apogeeUSB.CApnCamera_m_pvtTDIRate_set)
    __swig_setmethods__["m_pvtTDICounter"] = _apogeeUSB.CApnCamera_m_pvtTDICounter_set
    __swig_getmethods__["m_pvtTDICounter"] = _apogeeUSB.CApnCamera_m_pvtTDICounter_get
    if _newclass:m_pvtTDICounter = _swig_property(_apogeeUSB.CApnCamera_m_pvtTDICounter_get, _apogeeUSB.CApnCamera_m_pvtTDICounter_set)
    __swig_setmethods__["m_pvtFlushBinningV"] = _apogeeUSB.CApnCamera_m_pvtFlushBinningV_set
    __swig_getmethods__["m_pvtFlushBinningV"] = _apogeeUSB.CApnCamera_m_pvtFlushBinningV_get
    if _newclass:m_pvtFlushBinningV = _swig_property(_apogeeUSB.CApnCamera_m_pvtFlushBinningV_get, _apogeeUSB.CApnCamera_m_pvtFlushBinningV_set)
    __swig_setmethods__["m_pvtDigitizeOverscan"] = _apogeeUSB.CApnCamera_m_pvtDigitizeOverscan_set
    __swig_getmethods__["m_pvtDigitizeOverscan"] = _apogeeUSB.CApnCamera_m_pvtDigitizeOverscan_get
    if _newclass:m_pvtDigitizeOverscan = _swig_property(_apogeeUSB.CApnCamera_m_pvtDigitizeOverscan_get, _apogeeUSB.CApnCamera_m_pvtDigitizeOverscan_set)
    __swig_setmethods__["m_pvtSequenceBulkDownload"] = _apogeeUSB.CApnCamera_m_pvtSequenceBulkDownload_set
    __swig_getmethods__["m_pvtSequenceBulkDownload"] = _apogeeUSB.CApnCamera_m_pvtSequenceBulkDownload_get
    if _newclass:m_pvtSequenceBulkDownload = _swig_property(_apogeeUSB.CApnCamera_m_pvtSequenceBulkDownload_get, _apogeeUSB.CApnCamera_m_pvtSequenceBulkDownload_set)
    __swig_setmethods__["m_pvtSequenceDelay"] = _apogeeUSB.CApnCamera_m_pvtSequenceDelay_set
    __swig_getmethods__["m_pvtSequenceDelay"] = _apogeeUSB.CApnCamera_m_pvtSequenceDelay_get
    if _newclass:m_pvtSequenceDelay = _swig_property(_apogeeUSB.CApnCamera_m_pvtSequenceDelay_get, _apogeeUSB.CApnCamera_m_pvtSequenceDelay_set)
    __swig_setmethods__["m_pvtSequenceCounter"] = _apogeeUSB.CApnCamera_m_pvtSequenceCounter_set
    __swig_getmethods__["m_pvtSequenceCounter"] = _apogeeUSB.CApnCamera_m_pvtSequenceCounter_get
    if _newclass:m_pvtSequenceCounter = _swig_property(_apogeeUSB.CApnCamera_m_pvtSequenceCounter_get, _apogeeUSB.CApnCamera_m_pvtSequenceCounter_set)
    __swig_setmethods__["m_pvtFastSequence"] = _apogeeUSB.CApnCamera_m_pvtFastSequence_set
    __swig_getmethods__["m_pvtFastSequence"] = _apogeeUSB.CApnCamera_m_pvtFastSequence_get
    if _newclass:m_pvtFastSequence = _swig_property(_apogeeUSB.CApnCamera_m_pvtFastSequence_get, _apogeeUSB.CApnCamera_m_pvtFastSequence_set)
    __swig_setmethods__["m_pvtShutterStrobePosition"] = _apogeeUSB.CApnCamera_m_pvtShutterStrobePosition_set
    __swig_getmethods__["m_pvtShutterStrobePosition"] = _apogeeUSB.CApnCamera_m_pvtShutterStrobePosition_get
    if _newclass:m_pvtShutterStrobePosition = _swig_property(_apogeeUSB.CApnCamera_m_pvtShutterStrobePosition_get, _apogeeUSB.CApnCamera_m_pvtShutterStrobePosition_set)
    __swig_setmethods__["m_pvtShutterStrobePeriod"] = _apogeeUSB.CApnCamera_m_pvtShutterStrobePeriod_set
    __swig_getmethods__["m_pvtShutterStrobePeriod"] = _apogeeUSB.CApnCamera_m_pvtShutterStrobePeriod_get
    if _newclass:m_pvtShutterStrobePeriod = _swig_property(_apogeeUSB.CApnCamera_m_pvtShutterStrobePeriod_get, _apogeeUSB.CApnCamera_m_pvtShutterStrobePeriod_set)
    __swig_setmethods__["m_pvtShutterCloseDelay"] = _apogeeUSB.CApnCamera_m_pvtShutterCloseDelay_set
    __swig_getmethods__["m_pvtShutterCloseDelay"] = _apogeeUSB.CApnCamera_m_pvtShutterCloseDelay_get
    if _newclass:m_pvtShutterCloseDelay = _swig_property(_apogeeUSB.CApnCamera_m_pvtShutterCloseDelay_get, _apogeeUSB.CApnCamera_m_pvtShutterCloseDelay_set)
    __swig_setmethods__["m_pvtExposureTDIRows"] = _apogeeUSB.CApnCamera_m_pvtExposureTDIRows_set
    __swig_getmethods__["m_pvtExposureTDIRows"] = _apogeeUSB.CApnCamera_m_pvtExposureTDIRows_get
    if _newclass:m_pvtExposureTDIRows = _swig_property(_apogeeUSB.CApnCamera_m_pvtExposureTDIRows_get, _apogeeUSB.CApnCamera_m_pvtExposureTDIRows_set)
    __swig_setmethods__["m_pvtExposurePixelsH"] = _apogeeUSB.CApnCamera_m_pvtExposurePixelsH_set
    __swig_getmethods__["m_pvtExposurePixelsH"] = _apogeeUSB.CApnCamera_m_pvtExposurePixelsH_get
    if _newclass:m_pvtExposurePixelsH = _swig_property(_apogeeUSB.CApnCamera_m_pvtExposurePixelsH_get, _apogeeUSB.CApnCamera_m_pvtExposurePixelsH_set)
    __swig_setmethods__["m_pvtExposurePixelsV"] = _apogeeUSB.CApnCamera_m_pvtExposurePixelsV_set
    __swig_getmethods__["m_pvtExposurePixelsV"] = _apogeeUSB.CApnCamera_m_pvtExposurePixelsV_get
    if _newclass:m_pvtExposurePixelsV = _swig_property(_apogeeUSB.CApnCamera_m_pvtExposurePixelsV_get, _apogeeUSB.CApnCamera_m_pvtExposurePixelsV_set)
    __swig_setmethods__["m_pvtExposureTriggerGroup"] = _apogeeUSB.CApnCamera_m_pvtExposureTriggerGroup_set
    __swig_getmethods__["m_pvtExposureTriggerGroup"] = _apogeeUSB.CApnCamera_m_pvtExposureTriggerGroup_get
    if _newclass:m_pvtExposureTriggerGroup = _swig_property(_apogeeUSB.CApnCamera_m_pvtExposureTriggerGroup_get, _apogeeUSB.CApnCamera_m_pvtExposureTriggerGroup_set)
    __swig_setmethods__["m_pvtExposureTriggerEach"] = _apogeeUSB.CApnCamera_m_pvtExposureTriggerEach_set
    __swig_getmethods__["m_pvtExposureTriggerEach"] = _apogeeUSB.CApnCamera_m_pvtExposureTriggerEach_get
    if _newclass:m_pvtExposureTriggerEach = _swig_property(_apogeeUSB.CApnCamera_m_pvtExposureTriggerEach_get, _apogeeUSB.CApnCamera_m_pvtExposureTriggerEach_set)
    __swig_setmethods__["m_pvtExposureExternalShutter"] = _apogeeUSB.CApnCamera_m_pvtExposureExternalShutter_set
    __swig_getmethods__["m_pvtExposureExternalShutter"] = _apogeeUSB.CApnCamera_m_pvtExposureExternalShutter_get
    if _newclass:m_pvtExposureExternalShutter = _swig_property(_apogeeUSB.CApnCamera_m_pvtExposureExternalShutter_get, _apogeeUSB.CApnCamera_m_pvtExposureExternalShutter_set)
    __swig_setmethods__["m_pvtExposureImageCount"] = _apogeeUSB.CApnCamera_m_pvtExposureImageCount_set
    __swig_getmethods__["m_pvtExposureImageCount"] = _apogeeUSB.CApnCamera_m_pvtExposureImageCount_get
    if _newclass:m_pvtExposureImageCount = _swig_property(_apogeeUSB.CApnCamera_m_pvtExposureImageCount_get, _apogeeUSB.CApnCamera_m_pvtExposureImageCount_set)
    __swig_setmethods__["m_pvtExposureBulkDownload"] = _apogeeUSB.CApnCamera_m_pvtExposureBulkDownload_set
    __swig_getmethods__["m_pvtExposureBulkDownload"] = _apogeeUSB.CApnCamera_m_pvtExposureBulkDownload_get
    if _newclass:m_pvtExposureBulkDownload = _swig_property(_apogeeUSB.CApnCamera_m_pvtExposureBulkDownload_get, _apogeeUSB.CApnCamera_m_pvtExposureBulkDownload_set)
    __swig_setmethods__["m_pvtPreFlashEnable"] = _apogeeUSB.CApnCamera_m_pvtPreFlashEnable_set
    __swig_getmethods__["m_pvtPreFlashEnable"] = _apogeeUSB.CApnCamera_m_pvtPreFlashEnable_get
    if _newclass:m_pvtPreFlashEnable = _swig_property(_apogeeUSB.CApnCamera_m_pvtPreFlashEnable_get, _apogeeUSB.CApnCamera_m_pvtPreFlashEnable_set)
    __swig_setmethods__["m_pvtTwelveBitGain"] = _apogeeUSB.CApnCamera_m_pvtTwelveBitGain_set
    __swig_getmethods__["m_pvtTwelveBitGain"] = _apogeeUSB.CApnCamera_m_pvtTwelveBitGain_get
    if _newclass:m_pvtTwelveBitGain = _swig_property(_apogeeUSB.CApnCamera_m_pvtTwelveBitGain_get, _apogeeUSB.CApnCamera_m_pvtTwelveBitGain_set)
    __swig_setmethods__["m_pvtTwelveBitOffset"] = _apogeeUSB.CApnCamera_m_pvtTwelveBitOffset_set
    __swig_getmethods__["m_pvtTwelveBitOffset"] = _apogeeUSB.CApnCamera_m_pvtTwelveBitOffset_get
    if _newclass:m_pvtTwelveBitOffset = _swig_property(_apogeeUSB.CApnCamera_m_pvtTwelveBitOffset_get, _apogeeUSB.CApnCamera_m_pvtTwelveBitOffset_set)
    __swig_setmethods__["m_pvtAscentSixteenBitGainLeft"] = _apogeeUSB.CApnCamera_m_pvtAscentSixteenBitGainLeft_set
    __swig_getmethods__["m_pvtAscentSixteenBitGainLeft"] = _apogeeUSB.CApnCamera_m_pvtAscentSixteenBitGainLeft_get
    if _newclass:m_pvtAscentSixteenBitGainLeft = _swig_property(_apogeeUSB.CApnCamera_m_pvtAscentSixteenBitGainLeft_get, _apogeeUSB.CApnCamera_m_pvtAscentSixteenBitGainLeft_set)
    __swig_setmethods__["m_pvtAscentSixteenBitOffsetLeft"] = _apogeeUSB.CApnCamera_m_pvtAscentSixteenBitOffsetLeft_set
    __swig_getmethods__["m_pvtAscentSixteenBitOffsetLeft"] = _apogeeUSB.CApnCamera_m_pvtAscentSixteenBitOffsetLeft_get
    if _newclass:m_pvtAscentSixteenBitOffsetLeft = _swig_property(_apogeeUSB.CApnCamera_m_pvtAscentSixteenBitOffsetLeft_get, _apogeeUSB.CApnCamera_m_pvtAscentSixteenBitOffsetLeft_set)
    __swig_setmethods__["m_pvtAscentSixteenBitGainRight"] = _apogeeUSB.CApnCamera_m_pvtAscentSixteenBitGainRight_set
    __swig_getmethods__["m_pvtAscentSixteenBitGainRight"] = _apogeeUSB.CApnCamera_m_pvtAscentSixteenBitGainRight_get
    if _newclass:m_pvtAscentSixteenBitGainRight = _swig_property(_apogeeUSB.CApnCamera_m_pvtAscentSixteenBitGainRight_get, _apogeeUSB.CApnCamera_m_pvtAscentSixteenBitGainRight_set)
    __swig_setmethods__["m_pvtAscentSixteenBitOffsetRight"] = _apogeeUSB.CApnCamera_m_pvtAscentSixteenBitOffsetRight_set
    __swig_getmethods__["m_pvtAscentSixteenBitOffsetRight"] = _apogeeUSB.CApnCamera_m_pvtAscentSixteenBitOffsetRight_get
    if _newclass:m_pvtAscentSixteenBitOffsetRight = _swig_property(_apogeeUSB.CApnCamera_m_pvtAscentSixteenBitOffsetRight_get, _apogeeUSB.CApnCamera_m_pvtAscentSixteenBitOffsetRight_set)
    __swig_setmethods__["m_pvtDualReadout"] = _apogeeUSB.CApnCamera_m_pvtDualReadout_set
    __swig_getmethods__["m_pvtDualReadout"] = _apogeeUSB.CApnCamera_m_pvtDualReadout_get
    if _newclass:m_pvtDualReadout = _swig_property(_apogeeUSB.CApnCamera_m_pvtDualReadout_get, _apogeeUSB.CApnCamera_m_pvtDualReadout_set)
    __swig_setmethods__["m_pvtLedMode"] = _apogeeUSB.CApnCamera_m_pvtLedMode_set
    __swig_getmethods__["m_pvtLedMode"] = _apogeeUSB.CApnCamera_m_pvtLedMode_get
    if _newclass:m_pvtLedMode = _swig_property(_apogeeUSB.CApnCamera_m_pvtLedMode_get, _apogeeUSB.CApnCamera_m_pvtLedMode_set)
    __swig_setmethods__["m_pvtLedStateA"] = _apogeeUSB.CApnCamera_m_pvtLedStateA_set
    __swig_getmethods__["m_pvtLedStateA"] = _apogeeUSB.CApnCamera_m_pvtLedStateA_get
    if _newclass:m_pvtLedStateA = _swig_property(_apogeeUSB.CApnCamera_m_pvtLedStateA_get, _apogeeUSB.CApnCamera_m_pvtLedStateA_set)
    __swig_setmethods__["m_pvtLedStateB"] = _apogeeUSB.CApnCamera_m_pvtLedStateB_set
    __swig_getmethods__["m_pvtLedStateB"] = _apogeeUSB.CApnCamera_m_pvtLedStateB_get
    if _newclass:m_pvtLedStateB = _swig_property(_apogeeUSB.CApnCamera_m_pvtLedStateB_get, _apogeeUSB.CApnCamera_m_pvtLedStateB_set)
    __swig_setmethods__["m_pvtTestLedBrightness"] = _apogeeUSB.CApnCamera_m_pvtTestLedBrightness_set
    __swig_getmethods__["m_pvtTestLedBrightness"] = _apogeeUSB.CApnCamera_m_pvtTestLedBrightness_get
    if _newclass:m_pvtTestLedBrightness = _swig_property(_apogeeUSB.CApnCamera_m_pvtTestLedBrightness_get, _apogeeUSB.CApnCamera_m_pvtTestLedBrightness_set)
    __swig_setmethods__["m_pvtCoolerEnable"] = _apogeeUSB.CApnCamera_m_pvtCoolerEnable_set
    __swig_getmethods__["m_pvtCoolerEnable"] = _apogeeUSB.CApnCamera_m_pvtCoolerEnable_get
    if _newclass:m_pvtCoolerEnable = _swig_property(_apogeeUSB.CApnCamera_m_pvtCoolerEnable_get, _apogeeUSB.CApnCamera_m_pvtCoolerEnable_set)
    __swig_setmethods__["m_pvtFanMode"] = _apogeeUSB.CApnCamera_m_pvtFanMode_set
    __swig_getmethods__["m_pvtFanMode"] = _apogeeUSB.CApnCamera_m_pvtFanMode_get
    if _newclass:m_pvtFanMode = _swig_property(_apogeeUSB.CApnCamera_m_pvtFanMode_get, _apogeeUSB.CApnCamera_m_pvtFanMode_set)
    __swig_setmethods__["m_pvtCoolerBackoffPoint"] = _apogeeUSB.CApnCamera_m_pvtCoolerBackoffPoint_set
    __swig_getmethods__["m_pvtCoolerBackoffPoint"] = _apogeeUSB.CApnCamera_m_pvtCoolerBackoffPoint_get
    if _newclass:m_pvtCoolerBackoffPoint = _swig_property(_apogeeUSB.CApnCamera_m_pvtCoolerBackoffPoint_get, _apogeeUSB.CApnCamera_m_pvtCoolerBackoffPoint_set)
    __swig_setmethods__["m_pvtCoolerStatus"] = _apogeeUSB.CApnCamera_m_pvtCoolerStatus_set
    __swig_getmethods__["m_pvtCoolerStatus"] = _apogeeUSB.CApnCamera_m_pvtCoolerStatus_get
    if _newclass:m_pvtCoolerStatus = _swig_property(_apogeeUSB.CApnCamera_m_pvtCoolerStatus_get, _apogeeUSB.CApnCamera_m_pvtCoolerStatus_set)
    __swig_setmethods__["m_pvtImagingStatus"] = _apogeeUSB.CApnCamera_m_pvtImagingStatus_set
    __swig_getmethods__["m_pvtImagingStatus"] = _apogeeUSB.CApnCamera_m_pvtImagingStatus_get
    if _newclass:m_pvtImagingStatus = _swig_property(_apogeeUSB.CApnCamera_m_pvtImagingStatus_get, _apogeeUSB.CApnCamera_m_pvtImagingStatus_set)
    __swig_setmethods__["m_pvtPrevImagingStatus"] = _apogeeUSB.CApnCamera_m_pvtPrevImagingStatus_set
    __swig_getmethods__["m_pvtPrevImagingStatus"] = _apogeeUSB.CApnCamera_m_pvtPrevImagingStatus_get
    if _newclass:m_pvtPrevImagingStatus = _swig_property(_apogeeUSB.CApnCamera_m_pvtPrevImagingStatus_get, _apogeeUSB.CApnCamera_m_pvtPrevImagingStatus_set)
    __swig_setmethods__["m_pvtShutterState"] = _apogeeUSB.CApnCamera_m_pvtShutterState_set
    __swig_getmethods__["m_pvtShutterState"] = _apogeeUSB.CApnCamera_m_pvtShutterState_get
    if _newclass:m_pvtShutterState = _swig_property(_apogeeUSB.CApnCamera_m_pvtShutterState_get, _apogeeUSB.CApnCamera_m_pvtShutterState_set)
    __swig_setmethods__["m_pvtImageInProgress"] = _apogeeUSB.CApnCamera_m_pvtImageInProgress_set
    __swig_getmethods__["m_pvtImageInProgress"] = _apogeeUSB.CApnCamera_m_pvtImageInProgress_get
    if _newclass:m_pvtImageInProgress = _swig_property(_apogeeUSB.CApnCamera_m_pvtImageInProgress_get, _apogeeUSB.CApnCamera_m_pvtImageInProgress_set)
    __swig_setmethods__["m_pvtImageReady"] = _apogeeUSB.CApnCamera_m_pvtImageReady_set
    __swig_getmethods__["m_pvtImageReady"] = _apogeeUSB.CApnCamera_m_pvtImageReady_get
    if _newclass:m_pvtImageReady = _swig_property(_apogeeUSB.CApnCamera_m_pvtImageReady_get, _apogeeUSB.CApnCamera_m_pvtImageReady_set)
    __swig_setmethods__["m_pvtTriggerNormalEach"] = _apogeeUSB.CApnCamera_m_pvtTriggerNormalEach_set
    __swig_getmethods__["m_pvtTriggerNormalEach"] = _apogeeUSB.CApnCamera_m_pvtTriggerNormalEach_get
    if _newclass:m_pvtTriggerNormalEach = _swig_property(_apogeeUSB.CApnCamera_m_pvtTriggerNormalEach_get, _apogeeUSB.CApnCamera_m_pvtTriggerNormalEach_set)
    __swig_setmethods__["m_pvtTriggerNormalGroup"] = _apogeeUSB.CApnCamera_m_pvtTriggerNormalGroup_set
    __swig_getmethods__["m_pvtTriggerNormalGroup"] = _apogeeUSB.CApnCamera_m_pvtTriggerNormalGroup_get
    if _newclass:m_pvtTriggerNormalGroup = _swig_property(_apogeeUSB.CApnCamera_m_pvtTriggerNormalGroup_get, _apogeeUSB.CApnCamera_m_pvtTriggerNormalGroup_set)
    __swig_setmethods__["m_pvtTriggerTdiKineticsEach"] = _apogeeUSB.CApnCamera_m_pvtTriggerTdiKineticsEach_set
    __swig_getmethods__["m_pvtTriggerTdiKineticsEach"] = _apogeeUSB.CApnCamera_m_pvtTriggerTdiKineticsEach_get
    if _newclass:m_pvtTriggerTdiKineticsEach = _swig_property(_apogeeUSB.CApnCamera_m_pvtTriggerTdiKineticsEach_get, _apogeeUSB.CApnCamera_m_pvtTriggerTdiKineticsEach_set)
    __swig_setmethods__["m_pvtTriggerTdiKineticsGroup"] = _apogeeUSB.CApnCamera_m_pvtTriggerTdiKineticsGroup_set
    __swig_getmethods__["m_pvtTriggerTdiKineticsGroup"] = _apogeeUSB.CApnCamera_m_pvtTriggerTdiKineticsGroup_get
    if _newclass:m_pvtTriggerTdiKineticsGroup = _swig_property(_apogeeUSB.CApnCamera_m_pvtTriggerTdiKineticsGroup_get, _apogeeUSB.CApnCamera_m_pvtTriggerTdiKineticsGroup_set)
    __swig_setmethods__["m_pvtStatusReg"] = _apogeeUSB.CApnCamera_m_pvtStatusReg_set
    __swig_getmethods__["m_pvtStatusReg"] = _apogeeUSB.CApnCamera_m_pvtStatusReg_get
    if _newclass:m_pvtStatusReg = _swig_property(_apogeeUSB.CApnCamera_m_pvtStatusReg_get, _apogeeUSB.CApnCamera_m_pvtStatusReg_set)
    __swig_setmethods__["m_pvtCoolerDrive"] = _apogeeUSB.CApnCamera_m_pvtCoolerDrive_set
    __swig_getmethods__["m_pvtCoolerDrive"] = _apogeeUSB.CApnCamera_m_pvtCoolerDrive_get
    if _newclass:m_pvtCoolerDrive = _swig_property(_apogeeUSB.CApnCamera_m_pvtCoolerDrive_get, _apogeeUSB.CApnCamera_m_pvtCoolerDrive_set)
    __swig_setmethods__["m_pvtCurrentHeatsinkTemp"] = _apogeeUSB.CApnCamera_m_pvtCurrentHeatsinkTemp_set
    __swig_getmethods__["m_pvtCurrentHeatsinkTemp"] = _apogeeUSB.CApnCamera_m_pvtCurrentHeatsinkTemp_get
    if _newclass:m_pvtCurrentHeatsinkTemp = _swig_property(_apogeeUSB.CApnCamera_m_pvtCurrentHeatsinkTemp_get, _apogeeUSB.CApnCamera_m_pvtCurrentHeatsinkTemp_set)
    __swig_setmethods__["m_pvtCurrentCcdTemp"] = _apogeeUSB.CApnCamera_m_pvtCurrentCcdTemp_set
    __swig_getmethods__["m_pvtCurrentCcdTemp"] = _apogeeUSB.CApnCamera_m_pvtCurrentCcdTemp_get
    if _newclass:m_pvtCurrentCcdTemp = _swig_property(_apogeeUSB.CApnCamera_m_pvtCurrentCcdTemp_get, _apogeeUSB.CApnCamera_m_pvtCurrentCcdTemp_set)
    __swig_setmethods__["m_pvtInputVoltage"] = _apogeeUSB.CApnCamera_m_pvtInputVoltage_set
    __swig_getmethods__["m_pvtInputVoltage"] = _apogeeUSB.CApnCamera_m_pvtInputVoltage_get
    if _newclass:m_pvtInputVoltage = _swig_property(_apogeeUSB.CApnCamera_m_pvtInputVoltage_get, _apogeeUSB.CApnCamera_m_pvtInputVoltage_set)
    __swig_setmethods__["m_pvtIoPortDirection"] = _apogeeUSB.CApnCamera_m_pvtIoPortDirection_set
    __swig_getmethods__["m_pvtIoPortDirection"] = _apogeeUSB.CApnCamera_m_pvtIoPortDirection_get
    if _newclass:m_pvtIoPortDirection = _swig_property(_apogeeUSB.CApnCamera_m_pvtIoPortDirection_get, _apogeeUSB.CApnCamera_m_pvtIoPortDirection_set)
    __swig_setmethods__["m_pvtIoPortAssignment"] = _apogeeUSB.CApnCamera_m_pvtIoPortAssignment_set
    __swig_getmethods__["m_pvtIoPortAssignment"] = _apogeeUSB.CApnCamera_m_pvtIoPortAssignment_get
    if _newclass:m_pvtIoPortAssignment = _swig_property(_apogeeUSB.CApnCamera_m_pvtIoPortAssignment_get, _apogeeUSB.CApnCamera_m_pvtIoPortAssignment_set)
    __swig_setmethods__["m_pvtIoPortBlankingBits"] = _apogeeUSB.CApnCamera_m_pvtIoPortBlankingBits_set
    __swig_getmethods__["m_pvtIoPortBlankingBits"] = _apogeeUSB.CApnCamera_m_pvtIoPortBlankingBits_get
    if _newclass:m_pvtIoPortBlankingBits = _swig_property(_apogeeUSB.CApnCamera_m_pvtIoPortBlankingBits_get, _apogeeUSB.CApnCamera_m_pvtIoPortBlankingBits_set)
    __swig_setmethods__["m_pvtQueryStatusRetVal"] = _apogeeUSB.CApnCamera_m_pvtQueryStatusRetVal_set
    __swig_getmethods__["m_pvtQueryStatusRetVal"] = _apogeeUSB.CApnCamera_m_pvtQueryStatusRetVal_get
    if _newclass:m_pvtQueryStatusRetVal = _swig_property(_apogeeUSB.CApnCamera_m_pvtQueryStatusRetVal_get, _apogeeUSB.CApnCamera_m_pvtQueryStatusRetVal_set)
    __swig_setmethods__["m_pvtMostRecentFrame"] = _apogeeUSB.CApnCamera_m_pvtMostRecentFrame_set
    __swig_getmethods__["m_pvtMostRecentFrame"] = _apogeeUSB.CApnCamera_m_pvtMostRecentFrame_get
    if _newclass:m_pvtMostRecentFrame = _swig_property(_apogeeUSB.CApnCamera_m_pvtMostRecentFrame_get, _apogeeUSB.CApnCamera_m_pvtMostRecentFrame_set)
    __swig_setmethods__["m_pvtReadyFrame"] = _apogeeUSB.CApnCamera_m_pvtReadyFrame_set
    __swig_getmethods__["m_pvtReadyFrame"] = _apogeeUSB.CApnCamera_m_pvtReadyFrame_get
    if _newclass:m_pvtReadyFrame = _swig_property(_apogeeUSB.CApnCamera_m_pvtReadyFrame_get, _apogeeUSB.CApnCamera_m_pvtReadyFrame_set)
    __swig_setmethods__["m_pvtCurrentFrame"] = _apogeeUSB.CApnCamera_m_pvtCurrentFrame_set
    __swig_getmethods__["m_pvtCurrentFrame"] = _apogeeUSB.CApnCamera_m_pvtCurrentFrame_get
    if _newclass:m_pvtCurrentFrame = _swig_property(_apogeeUSB.CApnCamera_m_pvtCurrentFrame_get, _apogeeUSB.CApnCamera_m_pvtCurrentFrame_set)
    __swig_setmethods__["m_pvtGuideRAPlusDuration"] = _apogeeUSB.CApnCamera_m_pvtGuideRAPlusDuration_set
    __swig_getmethods__["m_pvtGuideRAPlusDuration"] = _apogeeUSB.CApnCamera_m_pvtGuideRAPlusDuration_get
    if _newclass:m_pvtGuideRAPlusDuration = _swig_property(_apogeeUSB.CApnCamera_m_pvtGuideRAPlusDuration_get, _apogeeUSB.CApnCamera_m_pvtGuideRAPlusDuration_set)
    __swig_setmethods__["m_pvtGuideRAMinusDuration"] = _apogeeUSB.CApnCamera_m_pvtGuideRAMinusDuration_set
    __swig_getmethods__["m_pvtGuideRAMinusDuration"] = _apogeeUSB.CApnCamera_m_pvtGuideRAMinusDuration_get
    if _newclass:m_pvtGuideRAMinusDuration = _swig_property(_apogeeUSB.CApnCamera_m_pvtGuideRAMinusDuration_get, _apogeeUSB.CApnCamera_m_pvtGuideRAMinusDuration_set)
    __swig_setmethods__["m_pvtGuideDecPlusDuration"] = _apogeeUSB.CApnCamera_m_pvtGuideDecPlusDuration_set
    __swig_getmethods__["m_pvtGuideDecPlusDuration"] = _apogeeUSB.CApnCamera_m_pvtGuideDecPlusDuration_get
    if _newclass:m_pvtGuideDecPlusDuration = _swig_property(_apogeeUSB.CApnCamera_m_pvtGuideDecPlusDuration_get, _apogeeUSB.CApnCamera_m_pvtGuideDecPlusDuration_set)
    __swig_setmethods__["m_pvtGuideDecMinusDuration"] = _apogeeUSB.CApnCamera_m_pvtGuideDecMinusDuration_set
    __swig_getmethods__["m_pvtGuideDecMinusDuration"] = _apogeeUSB.CApnCamera_m_pvtGuideDecMinusDuration_get
    if _newclass:m_pvtGuideDecMinusDuration = _swig_property(_apogeeUSB.CApnCamera_m_pvtGuideDecMinusDuration_get, _apogeeUSB.CApnCamera_m_pvtGuideDecMinusDuration_set)
    __swig_setmethods__["m_pvtFilterWheelType"] = _apogeeUSB.CApnCamera_m_pvtFilterWheelType_set
    __swig_getmethods__["m_pvtFilterWheelType"] = _apogeeUSB.CApnCamera_m_pvtFilterWheelType_get
    if _newclass:m_pvtFilterWheelType = _swig_property(_apogeeUSB.CApnCamera_m_pvtFilterWheelType_get, _apogeeUSB.CApnCamera_m_pvtFilterWheelType_set)
    __swig_setmethods__["m_pvtFilterMaxPositions"] = _apogeeUSB.CApnCamera_m_pvtFilterMaxPositions_set
    __swig_getmethods__["m_pvtFilterMaxPositions"] = _apogeeUSB.CApnCamera_m_pvtFilterMaxPositions_get
    if _newclass:m_pvtFilterMaxPositions = _swig_property(_apogeeUSB.CApnCamera_m_pvtFilterMaxPositions_get, _apogeeUSB.CApnCamera_m_pvtFilterMaxPositions_set)
    __swig_setmethods__["m_pvtRestoreTdiRowCount"] = _apogeeUSB.CApnCamera_m_pvtRestoreTdiRowCount_set
    __swig_getmethods__["m_pvtRestoreTdiRowCount"] = _apogeeUSB.CApnCamera_m_pvtRestoreTdiRowCount_get
    if _newclass:m_pvtRestoreTdiRowCount = _swig_property(_apogeeUSB.CApnCamera_m_pvtRestoreTdiRowCount_get, _apogeeUSB.CApnCamera_m_pvtRestoreTdiRowCount_set)
    __swig_setmethods__["m_pvtRestoreShutterControl"] = _apogeeUSB.CApnCamera_m_pvtRestoreShutterControl_set
    __swig_getmethods__["m_pvtRestoreShutterControl"] = _apogeeUSB.CApnCamera_m_pvtRestoreShutterControl_get
    if _newclass:m_pvtRestoreShutterControl = _swig_property(_apogeeUSB.CApnCamera_m_pvtRestoreShutterControl_get, _apogeeUSB.CApnCamera_m_pvtRestoreShutterControl_set)
    def SetPlatformConstants(self): return _apogeeUSB.CApnCamera_SetPlatformConstants(self)
    __swig_setmethods__["m_PlatformHBinningMax"] = _apogeeUSB.CApnCamera_m_PlatformHBinningMax_set
    __swig_getmethods__["m_PlatformHBinningMax"] = _apogeeUSB.CApnCamera_m_PlatformHBinningMax_get
    if _newclass:m_PlatformHBinningMax = _swig_property(_apogeeUSB.CApnCamera_m_PlatformHBinningMax_get, _apogeeUSB.CApnCamera_m_PlatformHBinningMax_set)
    __swig_setmethods__["m_PlatformVBinningMax"] = _apogeeUSB.CApnCamera_m_PlatformVBinningMax_set
    __swig_getmethods__["m_PlatformVBinningMax"] = _apogeeUSB.CApnCamera_m_PlatformVBinningMax_get
    if _newclass:m_PlatformVBinningMax = _swig_property(_apogeeUSB.CApnCamera_m_PlatformVBinningMax_get, _apogeeUSB.CApnCamera_m_PlatformVBinningMax_set)
    __swig_setmethods__["m_PlatformTimerResolution"] = _apogeeUSB.CApnCamera_m_PlatformTimerResolution_set
    __swig_getmethods__["m_PlatformTimerResolution"] = _apogeeUSB.CApnCamera_m_PlatformTimerResolution_get
    if _newclass:m_PlatformTimerResolution = _swig_property(_apogeeUSB.CApnCamera_m_PlatformTimerResolution_get, _apogeeUSB.CApnCamera_m_PlatformTimerResolution_set)
    __swig_setmethods__["m_PlatformPeriodTimerResolution"] = _apogeeUSB.CApnCamera_m_PlatformPeriodTimerResolution_set
    __swig_getmethods__["m_PlatformPeriodTimerResolution"] = _apogeeUSB.CApnCamera_m_PlatformPeriodTimerResolution_get
    if _newclass:m_PlatformPeriodTimerResolution = _swig_property(_apogeeUSB.CApnCamera_m_PlatformPeriodTimerResolution_get, _apogeeUSB.CApnCamera_m_PlatformPeriodTimerResolution_set)
    __swig_setmethods__["m_PlatformTimerOffsetCount"] = _apogeeUSB.CApnCamera_m_PlatformTimerOffsetCount_set
    __swig_getmethods__["m_PlatformTimerOffsetCount"] = _apogeeUSB.CApnCamera_m_PlatformTimerOffsetCount_get
    if _newclass:m_PlatformTimerOffsetCount = _swig_property(_apogeeUSB.CApnCamera_m_PlatformTimerOffsetCount_get, _apogeeUSB.CApnCamera_m_PlatformTimerOffsetCount_set)
    __swig_setmethods__["m_PlatformSequenceDelayResolution"] = _apogeeUSB.CApnCamera_m_PlatformSequenceDelayResolution_set
    __swig_getmethods__["m_PlatformSequenceDelayResolution"] = _apogeeUSB.CApnCamera_m_PlatformSequenceDelayResolution_get
    if _newclass:m_PlatformSequenceDelayResolution = _swig_property(_apogeeUSB.CApnCamera_m_PlatformSequenceDelayResolution_get, _apogeeUSB.CApnCamera_m_PlatformSequenceDelayResolution_set)
    __swig_setmethods__["m_PlatformSequenceDelayMaximum"] = _apogeeUSB.CApnCamera_m_PlatformSequenceDelayMaximum_set
    __swig_getmethods__["m_PlatformSequenceDelayMaximum"] = _apogeeUSB.CApnCamera_m_PlatformSequenceDelayMaximum_get
    if _newclass:m_PlatformSequenceDelayMaximum = _swig_property(_apogeeUSB.CApnCamera_m_PlatformSequenceDelayMaximum_get, _apogeeUSB.CApnCamera_m_PlatformSequenceDelayMaximum_set)
    __swig_setmethods__["m_PlatformSequenceDelayMinimum"] = _apogeeUSB.CApnCamera_m_PlatformSequenceDelayMinimum_set
    __swig_getmethods__["m_PlatformSequenceDelayMinimum"] = _apogeeUSB.CApnCamera_m_PlatformSequenceDelayMinimum_get
    if _newclass:m_PlatformSequenceDelayMinimum = _swig_property(_apogeeUSB.CApnCamera_m_PlatformSequenceDelayMinimum_get, _apogeeUSB.CApnCamera_m_PlatformSequenceDelayMinimum_set)
    __swig_setmethods__["m_PlatformExposureTimeMin"] = _apogeeUSB.CApnCamera_m_PlatformExposureTimeMin_set
    __swig_getmethods__["m_PlatformExposureTimeMin"] = _apogeeUSB.CApnCamera_m_PlatformExposureTimeMin_get
    if _newclass:m_PlatformExposureTimeMin = _swig_property(_apogeeUSB.CApnCamera_m_PlatformExposureTimeMin_get, _apogeeUSB.CApnCamera_m_PlatformExposureTimeMin_set)
    __swig_setmethods__["m_PlatformExposureTimeMax"] = _apogeeUSB.CApnCamera_m_PlatformExposureTimeMax_set
    __swig_getmethods__["m_PlatformExposureTimeMax"] = _apogeeUSB.CApnCamera_m_PlatformExposureTimeMax_get
    if _newclass:m_PlatformExposureTimeMax = _swig_property(_apogeeUSB.CApnCamera_m_PlatformExposureTimeMax_get, _apogeeUSB.CApnCamera_m_PlatformExposureTimeMax_set)
    __swig_setmethods__["m_PlatformTdiRateResolution"] = _apogeeUSB.CApnCamera_m_PlatformTdiRateResolution_set
    __swig_getmethods__["m_PlatformTdiRateResolution"] = _apogeeUSB.CApnCamera_m_PlatformTdiRateResolution_get
    if _newclass:m_PlatformTdiRateResolution = _swig_property(_apogeeUSB.CApnCamera_m_PlatformTdiRateResolution_get, _apogeeUSB.CApnCamera_m_PlatformTdiRateResolution_set)
    __swig_setmethods__["m_PlatformTdiRateMin"] = _apogeeUSB.CApnCamera_m_PlatformTdiRateMin_set
    __swig_getmethods__["m_PlatformTdiRateMin"] = _apogeeUSB.CApnCamera_m_PlatformTdiRateMin_get
    if _newclass:m_PlatformTdiRateMin = _swig_property(_apogeeUSB.CApnCamera_m_PlatformTdiRateMin_get, _apogeeUSB.CApnCamera_m_PlatformTdiRateMin_set)
    __swig_setmethods__["m_PlatformTdiRateMax"] = _apogeeUSB.CApnCamera_m_PlatformTdiRateMax_set
    __swig_getmethods__["m_PlatformTdiRateMax"] = _apogeeUSB.CApnCamera_m_PlatformTdiRateMax_get
    if _newclass:m_PlatformTdiRateMax = _swig_property(_apogeeUSB.CApnCamera_m_PlatformTdiRateMax_get, _apogeeUSB.CApnCamera_m_PlatformTdiRateMax_set)
    __swig_setmethods__["m_PlatformTdiRateDefault"] = _apogeeUSB.CApnCamera_m_PlatformTdiRateDefault_set
    __swig_getmethods__["m_PlatformTdiRateDefault"] = _apogeeUSB.CApnCamera_m_PlatformTdiRateDefault_get
    if _newclass:m_PlatformTdiRateDefault = _swig_property(_apogeeUSB.CApnCamera_m_PlatformTdiRateDefault_get, _apogeeUSB.CApnCamera_m_PlatformTdiRateDefault_set)
    __swig_setmethods__["m_PlatformVoltageResolution"] = _apogeeUSB.CApnCamera_m_PlatformVoltageResolution_set
    __swig_getmethods__["m_PlatformVoltageResolution"] = _apogeeUSB.CApnCamera_m_PlatformVoltageResolution_get
    if _newclass:m_PlatformVoltageResolution = _swig_property(_apogeeUSB.CApnCamera_m_PlatformVoltageResolution_get, _apogeeUSB.CApnCamera_m_PlatformVoltageResolution_set)
    __swig_setmethods__["m_PlatformShutterCloseDiff"] = _apogeeUSB.CApnCamera_m_PlatformShutterCloseDiff_set
    __swig_getmethods__["m_PlatformShutterCloseDiff"] = _apogeeUSB.CApnCamera_m_PlatformShutterCloseDiff_get
    if _newclass:m_PlatformShutterCloseDiff = _swig_property(_apogeeUSB.CApnCamera_m_PlatformShutterCloseDiff_get, _apogeeUSB.CApnCamera_m_PlatformShutterCloseDiff_set)
    __swig_setmethods__["m_PlatformStrobePositionMin"] = _apogeeUSB.CApnCamera_m_PlatformStrobePositionMin_set
    __swig_getmethods__["m_PlatformStrobePositionMin"] = _apogeeUSB.CApnCamera_m_PlatformStrobePositionMin_get
    if _newclass:m_PlatformStrobePositionMin = _swig_property(_apogeeUSB.CApnCamera_m_PlatformStrobePositionMin_get, _apogeeUSB.CApnCamera_m_PlatformStrobePositionMin_set)
    __swig_setmethods__["m_PlatformStrobePositionMax"] = _apogeeUSB.CApnCamera_m_PlatformStrobePositionMax_set
    __swig_getmethods__["m_PlatformStrobePositionMax"] = _apogeeUSB.CApnCamera_m_PlatformStrobePositionMax_get
    if _newclass:m_PlatformStrobePositionMax = _swig_property(_apogeeUSB.CApnCamera_m_PlatformStrobePositionMax_get, _apogeeUSB.CApnCamera_m_PlatformStrobePositionMax_set)
    __swig_setmethods__["m_PlatformStrobePositionDefault"] = _apogeeUSB.CApnCamera_m_PlatformStrobePositionDefault_set
    __swig_getmethods__["m_PlatformStrobePositionDefault"] = _apogeeUSB.CApnCamera_m_PlatformStrobePositionDefault_get
    if _newclass:m_PlatformStrobePositionDefault = _swig_property(_apogeeUSB.CApnCamera_m_PlatformStrobePositionDefault_get, _apogeeUSB.CApnCamera_m_PlatformStrobePositionDefault_set)
    __swig_setmethods__["m_PlatformStrobePeriodMin"] = _apogeeUSB.CApnCamera_m_PlatformStrobePeriodMin_set
    __swig_getmethods__["m_PlatformStrobePeriodMin"] = _apogeeUSB.CApnCamera_m_PlatformStrobePeriodMin_get
    if _newclass:m_PlatformStrobePeriodMin = _swig_property(_apogeeUSB.CApnCamera_m_PlatformStrobePeriodMin_get, _apogeeUSB.CApnCamera_m_PlatformStrobePeriodMin_set)
    __swig_setmethods__["m_PlatformStrobePeriodMax"] = _apogeeUSB.CApnCamera_m_PlatformStrobePeriodMax_set
    __swig_getmethods__["m_PlatformStrobePeriodMax"] = _apogeeUSB.CApnCamera_m_PlatformStrobePeriodMax_get
    if _newclass:m_PlatformStrobePeriodMax = _swig_property(_apogeeUSB.CApnCamera_m_PlatformStrobePeriodMax_get, _apogeeUSB.CApnCamera_m_PlatformStrobePeriodMax_set)
    __swig_setmethods__["m_PlatformStrobePeriodDefault"] = _apogeeUSB.CApnCamera_m_PlatformStrobePeriodDefault_set
    __swig_getmethods__["m_PlatformStrobePeriodDefault"] = _apogeeUSB.CApnCamera_m_PlatformStrobePeriodDefault_get
    if _newclass:m_PlatformStrobePeriodDefault = _swig_property(_apogeeUSB.CApnCamera_m_PlatformStrobePeriodDefault_get, _apogeeUSB.CApnCamera_m_PlatformStrobePeriodDefault_set)
    __swig_setmethods__["m_PlatformTempCounts"] = _apogeeUSB.CApnCamera_m_PlatformTempCounts_set
    __swig_getmethods__["m_PlatformTempCounts"] = _apogeeUSB.CApnCamera_m_PlatformTempCounts_get
    if _newclass:m_PlatformTempCounts = _swig_property(_apogeeUSB.CApnCamera_m_PlatformTempCounts_get, _apogeeUSB.CApnCamera_m_PlatformTempCounts_set)
    __swig_setmethods__["m_PlatformTempKelvinScaleOffset"] = _apogeeUSB.CApnCamera_m_PlatformTempKelvinScaleOffset_set
    __swig_getmethods__["m_PlatformTempKelvinScaleOffset"] = _apogeeUSB.CApnCamera_m_PlatformTempKelvinScaleOffset_get
    if _newclass:m_PlatformTempKelvinScaleOffset = _swig_property(_apogeeUSB.CApnCamera_m_PlatformTempKelvinScaleOffset_get, _apogeeUSB.CApnCamera_m_PlatformTempKelvinScaleOffset_set)
    __swig_setmethods__["m_PlatformTempSetpointMin"] = _apogeeUSB.CApnCamera_m_PlatformTempSetpointMin_set
    __swig_getmethods__["m_PlatformTempSetpointMin"] = _apogeeUSB.CApnCamera_m_PlatformTempSetpointMin_get
    if _newclass:m_PlatformTempSetpointMin = _swig_property(_apogeeUSB.CApnCamera_m_PlatformTempSetpointMin_get, _apogeeUSB.CApnCamera_m_PlatformTempSetpointMin_set)
    __swig_setmethods__["m_PlatformTempSetpointMax"] = _apogeeUSB.CApnCamera_m_PlatformTempSetpointMax_set
    __swig_getmethods__["m_PlatformTempSetpointMax"] = _apogeeUSB.CApnCamera_m_PlatformTempSetpointMax_get
    if _newclass:m_PlatformTempSetpointMax = _swig_property(_apogeeUSB.CApnCamera_m_PlatformTempSetpointMax_get, _apogeeUSB.CApnCamera_m_PlatformTempSetpointMax_set)
    __swig_setmethods__["m_PlatformTempHeatsinkMin"] = _apogeeUSB.CApnCamera_m_PlatformTempHeatsinkMin_set
    __swig_getmethods__["m_PlatformTempHeatsinkMin"] = _apogeeUSB.CApnCamera_m_PlatformTempHeatsinkMin_get
    if _newclass:m_PlatformTempHeatsinkMin = _swig_property(_apogeeUSB.CApnCamera_m_PlatformTempHeatsinkMin_get, _apogeeUSB.CApnCamera_m_PlatformTempHeatsinkMin_set)
    __swig_setmethods__["m_PlatformTempHeatsinkMax"] = _apogeeUSB.CApnCamera_m_PlatformTempHeatsinkMax_set
    __swig_getmethods__["m_PlatformTempHeatsinkMax"] = _apogeeUSB.CApnCamera_m_PlatformTempHeatsinkMax_get
    if _newclass:m_PlatformTempHeatsinkMax = _swig_property(_apogeeUSB.CApnCamera_m_PlatformTempHeatsinkMax_get, _apogeeUSB.CApnCamera_m_PlatformTempHeatsinkMax_set)
    __swig_setmethods__["m_PlatformTempSetpointZeroPoint"] = _apogeeUSB.CApnCamera_m_PlatformTempSetpointZeroPoint_set
    __swig_getmethods__["m_PlatformTempSetpointZeroPoint"] = _apogeeUSB.CApnCamera_m_PlatformTempSetpointZeroPoint_get
    if _newclass:m_PlatformTempSetpointZeroPoint = _swig_property(_apogeeUSB.CApnCamera_m_PlatformTempSetpointZeroPoint_get, _apogeeUSB.CApnCamera_m_PlatformTempSetpointZeroPoint_set)
    __swig_setmethods__["m_PlatformTempHeatsinkZeroPoint"] = _apogeeUSB.CApnCamera_m_PlatformTempHeatsinkZeroPoint_set
    __swig_getmethods__["m_PlatformTempHeatsinkZeroPoint"] = _apogeeUSB.CApnCamera_m_PlatformTempHeatsinkZeroPoint_get
    if _newclass:m_PlatformTempHeatsinkZeroPoint = _swig_property(_apogeeUSB.CApnCamera_m_PlatformTempHeatsinkZeroPoint_get, _apogeeUSB.CApnCamera_m_PlatformTempHeatsinkZeroPoint_set)
    __swig_setmethods__["m_PlatformTempDegreesPerBit"] = _apogeeUSB.CApnCamera_m_PlatformTempDegreesPerBit_set
    __swig_getmethods__["m_PlatformTempDegreesPerBit"] = _apogeeUSB.CApnCamera_m_PlatformTempDegreesPerBit_get
    if _newclass:m_PlatformTempDegreesPerBit = _swig_property(_apogeeUSB.CApnCamera_m_PlatformTempDegreesPerBit_get, _apogeeUSB.CApnCamera_m_PlatformTempDegreesPerBit_set)
    __swig_setmethods__["m_PlatformFanSpeedOff"] = _apogeeUSB.CApnCamera_m_PlatformFanSpeedOff_set
    __swig_getmethods__["m_PlatformFanSpeedOff"] = _apogeeUSB.CApnCamera_m_PlatformFanSpeedOff_get
    if _newclass:m_PlatformFanSpeedOff = _swig_property(_apogeeUSB.CApnCamera_m_PlatformFanSpeedOff_get, _apogeeUSB.CApnCamera_m_PlatformFanSpeedOff_set)
    __swig_setmethods__["m_PlatformFanSpeedLow"] = _apogeeUSB.CApnCamera_m_PlatformFanSpeedLow_set
    __swig_getmethods__["m_PlatformFanSpeedLow"] = _apogeeUSB.CApnCamera_m_PlatformFanSpeedLow_get
    if _newclass:m_PlatformFanSpeedLow = _swig_property(_apogeeUSB.CApnCamera_m_PlatformFanSpeedLow_get, _apogeeUSB.CApnCamera_m_PlatformFanSpeedLow_set)
    __swig_setmethods__["m_PlatformFanSpeedMedium"] = _apogeeUSB.CApnCamera_m_PlatformFanSpeedMedium_set
    __swig_getmethods__["m_PlatformFanSpeedMedium"] = _apogeeUSB.CApnCamera_m_PlatformFanSpeedMedium_get
    if _newclass:m_PlatformFanSpeedMedium = _swig_property(_apogeeUSB.CApnCamera_m_PlatformFanSpeedMedium_get, _apogeeUSB.CApnCamera_m_PlatformFanSpeedMedium_set)
    __swig_setmethods__["m_PlatformFanSpeedHigh"] = _apogeeUSB.CApnCamera_m_PlatformFanSpeedHigh_set
    __swig_getmethods__["m_PlatformFanSpeedHigh"] = _apogeeUSB.CApnCamera_m_PlatformFanSpeedHigh_get
    if _newclass:m_PlatformFanSpeedHigh = _swig_property(_apogeeUSB.CApnCamera_m_PlatformFanSpeedHigh_get, _apogeeUSB.CApnCamera_m_PlatformFanSpeedHigh_set)
    __swig_setmethods__["m_PlatformGuiderRelayResolution"] = _apogeeUSB.CApnCamera_m_PlatformGuiderRelayResolution_set
    __swig_getmethods__["m_PlatformGuiderRelayResolution"] = _apogeeUSB.CApnCamera_m_PlatformGuiderRelayResolution_get
    if _newclass:m_PlatformGuiderRelayResolution = _swig_property(_apogeeUSB.CApnCamera_m_PlatformGuiderRelayResolution_get, _apogeeUSB.CApnCamera_m_PlatformGuiderRelayResolution_set)
    __swig_setmethods__["m_PlatformGuiderRelayMin"] = _apogeeUSB.CApnCamera_m_PlatformGuiderRelayMin_set
    __swig_getmethods__["m_PlatformGuiderRelayMin"] = _apogeeUSB.CApnCamera_m_PlatformGuiderRelayMin_get
    if _newclass:m_PlatformGuiderRelayMin = _swig_property(_apogeeUSB.CApnCamera_m_PlatformGuiderRelayMin_get, _apogeeUSB.CApnCamera_m_PlatformGuiderRelayMin_set)
    __swig_setmethods__["m_PlatformGuiderRelayMax"] = _apogeeUSB.CApnCamera_m_PlatformGuiderRelayMax_set
    __swig_getmethods__["m_PlatformGuiderRelayMax"] = _apogeeUSB.CApnCamera_m_PlatformGuiderRelayMax_get
    if _newclass:m_PlatformGuiderRelayMax = _swig_property(_apogeeUSB.CApnCamera_m_PlatformGuiderRelayMax_get, _apogeeUSB.CApnCamera_m_PlatformGuiderRelayMax_set)
    __swig_setmethods__["m_PlatformGuiderRelayOpenTime"] = _apogeeUSB.CApnCamera_m_PlatformGuiderRelayOpenTime_set
    __swig_getmethods__["m_PlatformGuiderRelayOpenTime"] = _apogeeUSB.CApnCamera_m_PlatformGuiderRelayOpenTime_get
    if _newclass:m_PlatformGuiderRelayOpenTime = _swig_property(_apogeeUSB.CApnCamera_m_PlatformGuiderRelayOpenTime_get, _apogeeUSB.CApnCamera_m_PlatformGuiderRelayOpenTime_set)
    __swig_setmethods__["m_PlatformGuiderRelayCloseTime"] = _apogeeUSB.CApnCamera_m_PlatformGuiderRelayCloseTime_set
    __swig_getmethods__["m_PlatformGuiderRelayCloseTime"] = _apogeeUSB.CApnCamera_m_PlatformGuiderRelayCloseTime_get
    if _newclass:m_PlatformGuiderRelayCloseTime = _swig_property(_apogeeUSB.CApnCamera_m_PlatformGuiderRelayCloseTime_get, _apogeeUSB.CApnCamera_m_PlatformGuiderRelayCloseTime_set)
    __swig_setmethods__["m_PlatformPreflashDuration"] = _apogeeUSB.CApnCamera_m_PlatformPreflashDuration_set
    __swig_getmethods__["m_PlatformPreflashDuration"] = _apogeeUSB.CApnCamera_m_PlatformPreflashDuration_get
    if _newclass:m_PlatformPreflashDuration = _swig_property(_apogeeUSB.CApnCamera_m_PlatformPreflashDuration_get, _apogeeUSB.CApnCamera_m_PlatformPreflashDuration_set)
    __swig_setmethods__["m_pvtConnectionOpen"] = _apogeeUSB.CApnCamera_m_pvtConnectionOpen_set
    __swig_getmethods__["m_pvtConnectionOpen"] = _apogeeUSB.CApnCamera_m_pvtConnectionOpen_get
    if _newclass:m_pvtConnectionOpen = _swig_property(_apogeeUSB.CApnCamera_m_pvtConnectionOpen_get, _apogeeUSB.CApnCamera_m_pvtConnectionOpen_set)
    __swig_setmethods__["m_SysDeviceName"] = _apogeeUSB.CApnCamera_m_SysDeviceName_set
    __swig_getmethods__["m_SysDeviceName"] = _apogeeUSB.CApnCamera_m_SysDeviceName_get
    if _newclass:m_SysDeviceName = _swig_property(_apogeeUSB.CApnCamera_m_SysDeviceName_get, _apogeeUSB.CApnCamera_m_SysDeviceName_set)
    __swig_setmethods__["m_CamIdA"] = _apogeeUSB.CApnCamera_m_CamIdA_set
    __swig_getmethods__["m_CamIdA"] = _apogeeUSB.CApnCamera_m_CamIdA_get
    if _newclass:m_CamIdA = _swig_property(_apogeeUSB.CApnCamera_m_CamIdA_get, _apogeeUSB.CApnCamera_m_CamIdA_set)
    __swig_setmethods__["m_CamIdB"] = _apogeeUSB.CApnCamera_m_CamIdB_set
    __swig_getmethods__["m_CamIdB"] = _apogeeUSB.CApnCamera_m_CamIdB_get
    if _newclass:m_CamIdB = _swig_property(_apogeeUSB.CApnCamera_m_CamIdB_get, _apogeeUSB.CApnCamera_m_CamIdB_set)
    __swig_setmethods__["m_Option"] = _apogeeUSB.CApnCamera_m_Option_set
    __swig_getmethods__["m_Option"] = _apogeeUSB.CApnCamera_m_Option_get
    if _newclass:m_Option = _swig_property(_apogeeUSB.CApnCamera_m_Option_get, _apogeeUSB.CApnCamera_m_Option_set)
    __swig_setmethods__["m_SysImgSizeBytes"] = _apogeeUSB.CApnCamera_m_SysImgSizeBytes_set
    __swig_getmethods__["m_SysImgSizeBytes"] = _apogeeUSB.CApnCamera_m_SysImgSizeBytes_get
    if _newclass:m_SysImgSizeBytes = _swig_property(_apogeeUSB.CApnCamera_m_SysImgSizeBytes_get, _apogeeUSB.CApnCamera_m_SysImgSizeBytes_set)
    __swig_setmethods__["m_pvtVendorId"] = _apogeeUSB.CApnCamera_m_pvtVendorId_set
    __swig_getmethods__["m_pvtVendorId"] = _apogeeUSB.CApnCamera_m_pvtVendorId_get
    if _newclass:m_pvtVendorId = _swig_property(_apogeeUSB.CApnCamera_m_pvtVendorId_get, _apogeeUSB.CApnCamera_m_pvtVendorId_set)
    __swig_setmethods__["m_pvtProductId"] = _apogeeUSB.CApnCamera_m_pvtProductId_set
    __swig_getmethods__["m_pvtProductId"] = _apogeeUSB.CApnCamera_m_pvtProductId_get
    if _newclass:m_pvtProductId = _swig_property(_apogeeUSB.CApnCamera_m_pvtProductId_get, _apogeeUSB.CApnCamera_m_pvtProductId_set)
    __swig_setmethods__["m_pvtDeviceId"] = _apogeeUSB.CApnCamera_m_pvtDeviceId_set
    __swig_getmethods__["m_pvtDeviceId"] = _apogeeUSB.CApnCamera_m_pvtDeviceId_get
    if _newclass:m_pvtDeviceId = _swig_property(_apogeeUSB.CApnCamera_m_pvtDeviceId_get, _apogeeUSB.CApnCamera_m_pvtDeviceId_set)
    __swig_setmethods__["m_SysDriverVersion"] = _apogeeUSB.CApnCamera_m_SysDriverVersion_set
    __swig_getmethods__["m_SysDriverVersion"] = _apogeeUSB.CApnCamera_m_SysDriverVersion_get
    if _newclass:m_SysDriverVersion = _swig_property(_apogeeUSB.CApnCamera_m_SysDriverVersion_get, _apogeeUSB.CApnCamera_m_SysDriverVersion_set)
    __swig_setmethods__["m_pvtSequenceImagesDownloaded"] = _apogeeUSB.CApnCamera_m_pvtSequenceImagesDownloaded_set
    __swig_getmethods__["m_pvtSequenceImagesDownloaded"] = _apogeeUSB.CApnCamera_m_pvtSequenceImagesDownloaded_get
    if _newclass:m_pvtSequenceImagesDownloaded = _swig_property(_apogeeUSB.CApnCamera_m_pvtSequenceImagesDownloaded_get, _apogeeUSB.CApnCamera_m_pvtSequenceImagesDownloaded_set)
    __swig_setmethods__["m_pvtNumImages"] = _apogeeUSB.CApnCamera_m_pvtNumImages_set
    __swig_getmethods__["m_pvtNumImages"] = _apogeeUSB.CApnCamera_m_pvtNumImages_get
    if _newclass:m_pvtNumImages = _swig_property(_apogeeUSB.CApnCamera_m_pvtNumImages_get, _apogeeUSB.CApnCamera_m_pvtNumImages_set)
    __swig_setmethods__["m_pvtTdiLinesDownloaded"] = _apogeeUSB.CApnCamera_m_pvtTdiLinesDownloaded_set
    __swig_getmethods__["m_pvtTdiLinesDownloaded"] = _apogeeUSB.CApnCamera_m_pvtTdiLinesDownloaded_get
    if _newclass:m_pvtTdiLinesDownloaded = _swig_property(_apogeeUSB.CApnCamera_m_pvtTdiLinesDownloaded_get, _apogeeUSB.CApnCamera_m_pvtTdiLinesDownloaded_set)
    __swig_setmethods__["m_HostAddr"] = _apogeeUSB.CApnCamera_m_HostAddr_set
    __swig_getmethods__["m_HostAddr"] = _apogeeUSB.CApnCamera_m_HostAddr_get
    if _newclass:m_HostAddr = _swig_property(_apogeeUSB.CApnCamera_m_HostAddr_get, _apogeeUSB.CApnCamera_m_HostAddr_set)
    __swig_setmethods__["m_ImageSizeBytes"] = _apogeeUSB.CApnCamera_m_ImageSizeBytes_set
    __swig_getmethods__["m_ImageSizeBytes"] = _apogeeUSB.CApnCamera_m_ImageSizeBytes_get
    if _newclass:m_ImageSizeBytes = _swig_property(_apogeeUSB.CApnCamera_m_ImageSizeBytes_get, _apogeeUSB.CApnCamera_m_ImageSizeBytes_set)
    __swig_setmethods__["m_ImageInProgress"] = _apogeeUSB.CApnCamera_m_ImageInProgress_set
    __swig_getmethods__["m_ImageInProgress"] = _apogeeUSB.CApnCamera_m_ImageInProgress_get
    if _newclass:m_ImageInProgress = _swig_property(_apogeeUSB.CApnCamera_m_ImageInProgress_get, _apogeeUSB.CApnCamera_m_ImageInProgress_set)
    __swig_setmethods__["m_FastDownload"] = _apogeeUSB.CApnCamera_m_FastDownload_set
    __swig_getmethods__["m_FastDownload"] = _apogeeUSB.CApnCamera_m_FastDownload_get
    if _newclass:m_FastDownload = _swig_property(_apogeeUSB.CApnCamera_m_FastDownload_get, _apogeeUSB.CApnCamera_m_FastDownload_set)
    __swig_setmethods__["m_pvtExposeWidth"] = _apogeeUSB.CApnCamera_m_pvtExposeWidth_set
    __swig_getmethods__["m_pvtExposeWidth"] = _apogeeUSB.CApnCamera_m_pvtExposeWidth_get
    if _newclass:m_pvtExposeWidth = _swig_property(_apogeeUSB.CApnCamera_m_pvtExposeWidth_get, _apogeeUSB.CApnCamera_m_pvtExposeWidth_set)
    __swig_setmethods__["m_pvtExposeHeight"] = _apogeeUSB.CApnCamera_m_pvtExposeHeight_set
    __swig_getmethods__["m_pvtExposeHeight"] = _apogeeUSB.CApnCamera_m_pvtExposeHeight_get
    if _newclass:m_pvtExposeHeight = _swig_property(_apogeeUSB.CApnCamera_m_pvtExposeHeight_get, _apogeeUSB.CApnCamera_m_pvtExposeHeight_set)
    __swig_setmethods__["m_pvtExposeExternalShutter"] = _apogeeUSB.CApnCamera_m_pvtExposeExternalShutter_set
    __swig_getmethods__["m_pvtExposeExternalShutter"] = _apogeeUSB.CApnCamera_m_pvtExposeExternalShutter_get
    if _newclass:m_pvtExposeExternalShutter = _swig_property(_apogeeUSB.CApnCamera_m_pvtExposeExternalShutter_get, _apogeeUSB.CApnCamera_m_pvtExposeExternalShutter_set)
    __swig_setmethods__["m_pvtExposeCameraMode"] = _apogeeUSB.CApnCamera_m_pvtExposeCameraMode_set
    __swig_getmethods__["m_pvtExposeCameraMode"] = _apogeeUSB.CApnCamera_m_pvtExposeCameraMode_get
    if _newclass:m_pvtExposeCameraMode = _swig_property(_apogeeUSB.CApnCamera_m_pvtExposeCameraMode_get, _apogeeUSB.CApnCamera_m_pvtExposeCameraMode_set)
    __swig_setmethods__["m_pvtExposeSequenceBulkDownload"] = _apogeeUSB.CApnCamera_m_pvtExposeSequenceBulkDownload_set
    __swig_getmethods__["m_pvtExposeSequenceBulkDownload"] = _apogeeUSB.CApnCamera_m_pvtExposeSequenceBulkDownload_get
    if _newclass:m_pvtExposeSequenceBulkDownload = _swig_property(_apogeeUSB.CApnCamera_m_pvtExposeSequenceBulkDownload_get, _apogeeUSB.CApnCamera_m_pvtExposeSequenceBulkDownload_set)
    __swig_setmethods__["m_pvtExposeCI"] = _apogeeUSB.CApnCamera_m_pvtExposeCI_set
    __swig_getmethods__["m_pvtExposeCI"] = _apogeeUSB.CApnCamera_m_pvtExposeCI_get
    if _newclass:m_pvtExposeCI = _swig_property(_apogeeUSB.CApnCamera_m_pvtExposeCI_get, _apogeeUSB.CApnCamera_m_pvtExposeCI_set)
    __swig_setmethods__["m_pvtExposeHBinning"] = _apogeeUSB.CApnCamera_m_pvtExposeHBinning_set
    __swig_getmethods__["m_pvtExposeHBinning"] = _apogeeUSB.CApnCamera_m_pvtExposeHBinning_get
    if _newclass:m_pvtExposeHBinning = _swig_property(_apogeeUSB.CApnCamera_m_pvtExposeHBinning_get, _apogeeUSB.CApnCamera_m_pvtExposeHBinning_set)
    __swig_setmethods__["m_pvtExposeBitsPerPixel"] = _apogeeUSB.CApnCamera_m_pvtExposeBitsPerPixel_set
    __swig_getmethods__["m_pvtExposeBitsPerPixel"] = _apogeeUSB.CApnCamera_m_pvtExposeBitsPerPixel_get
    if _newclass:m_pvtExposeBitsPerPixel = _swig_property(_apogeeUSB.CApnCamera_m_pvtExposeBitsPerPixel_get, _apogeeUSB.CApnCamera_m_pvtExposeBitsPerPixel_set)
    __swig_setmethods__["m_pvtBitsPerPixel"] = _apogeeUSB.CApnCamera_m_pvtBitsPerPixel_set
    __swig_getmethods__["m_pvtBitsPerPixel"] = _apogeeUSB.CApnCamera_m_pvtBitsPerPixel_get
    if _newclass:m_pvtBitsPerPixel = _swig_property(_apogeeUSB.CApnCamera_m_pvtBitsPerPixel_get, _apogeeUSB.CApnCamera_m_pvtBitsPerPixel_set)
    __swig_setmethods__["m_pvtExposeDualReadout"] = _apogeeUSB.CApnCamera_m_pvtExposeDualReadout_set
    __swig_getmethods__["m_pvtExposeDualReadout"] = _apogeeUSB.CApnCamera_m_pvtExposeDualReadout_get
    if _newclass:m_pvtExposeDualReadout = _swig_property(_apogeeUSB.CApnCamera_m_pvtExposeDualReadout_get, _apogeeUSB.CApnCamera_m_pvtExposeDualReadout_set)
    __swig_setmethods__["m_cameraNumber"] = _apogeeUSB.CApnCamera_m_cameraNumber_set
    __swig_getmethods__["m_cameraNumber"] = _apogeeUSB.CApnCamera_m_cameraNumber_get
    if _newclass:m_cameraNumber = _swig_property(_apogeeUSB.CApnCamera_m_cameraNumber_get, _apogeeUSB.CApnCamera_m_cameraNumber_set)
    def sensorInfo(self): return _apogeeUSB.CApnCamera_sensorInfo(self)
    __swig_setmethods__["m_Sensor"] = _apogeeUSB.CApnCamera_m_Sensor_set
    __swig_getmethods__["m_Sensor"] = _apogeeUSB.CApnCamera_m_Sensor_get
    if _newclass:m_Sensor = _swig_property(_apogeeUSB.CApnCamera_m_Sensor_get, _apogeeUSB.CApnCamera_m_Sensor_set)
    __swig_setmethods__["m_CameraModel"] = _apogeeUSB.CApnCamera_m_CameraModel_set
    __swig_getmethods__["m_CameraModel"] = _apogeeUSB.CApnCamera_m_CameraModel_get
    if _newclass:m_CameraModel = _swig_property(_apogeeUSB.CApnCamera_m_CameraModel_get, _apogeeUSB.CApnCamera_m_CameraModel_set)
    __swig_setmethods__["m_CameraId"] = _apogeeUSB.CApnCamera_m_CameraId_set
    __swig_getmethods__["m_CameraId"] = _apogeeUSB.CApnCamera_m_CameraId_get
    if _newclass:m_CameraId = _swig_property(_apogeeUSB.CApnCamera_m_CameraId_get, _apogeeUSB.CApnCamera_m_CameraId_set)
    __swig_setmethods__["m_InterlineCCD"] = _apogeeUSB.CApnCamera_m_InterlineCCD_set
    __swig_getmethods__["m_InterlineCCD"] = _apogeeUSB.CApnCamera_m_InterlineCCD_get
    if _newclass:m_InterlineCCD = _swig_property(_apogeeUSB.CApnCamera_m_InterlineCCD_get, _apogeeUSB.CApnCamera_m_InterlineCCD_set)
    __swig_setmethods__["m_SupportsSerialA"] = _apogeeUSB.CApnCamera_m_SupportsSerialA_set
    __swig_getmethods__["m_SupportsSerialA"] = _apogeeUSB.CApnCamera_m_SupportsSerialA_get
    if _newclass:m_SupportsSerialA = _swig_property(_apogeeUSB.CApnCamera_m_SupportsSerialA_get, _apogeeUSB.CApnCamera_m_SupportsSerialA_set)
    __swig_setmethods__["m_SupportsSerialB"] = _apogeeUSB.CApnCamera_m_SupportsSerialB_set
    __swig_getmethods__["m_SupportsSerialB"] = _apogeeUSB.CApnCamera_m_SupportsSerialB_get
    if _newclass:m_SupportsSerialB = _swig_property(_apogeeUSB.CApnCamera_m_SupportsSerialB_get, _apogeeUSB.CApnCamera_m_SupportsSerialB_set)
    __swig_setmethods__["m_SensorTypeCCD"] = _apogeeUSB.CApnCamera_m_SensorTypeCCD_set
    __swig_getmethods__["m_SensorTypeCCD"] = _apogeeUSB.CApnCamera_m_SensorTypeCCD_get
    if _newclass:m_SensorTypeCCD = _swig_property(_apogeeUSB.CApnCamera_m_SensorTypeCCD_get, _apogeeUSB.CApnCamera_m_SensorTypeCCD_set)
    __swig_setmethods__["m_TotalColumns"] = _apogeeUSB.CApnCamera_m_TotalColumns_set
    __swig_getmethods__["m_TotalColumns"] = _apogeeUSB.CApnCamera_m_TotalColumns_get
    if _newclass:m_TotalColumns = _swig_property(_apogeeUSB.CApnCamera_m_TotalColumns_get, _apogeeUSB.CApnCamera_m_TotalColumns_set)
    __swig_setmethods__["m_ImagingColumns"] = _apogeeUSB.CApnCamera_m_ImagingColumns_set
    __swig_getmethods__["m_ImagingColumns"] = _apogeeUSB.CApnCamera_m_ImagingColumns_get
    if _newclass:m_ImagingColumns = _swig_property(_apogeeUSB.CApnCamera_m_ImagingColumns_get, _apogeeUSB.CApnCamera_m_ImagingColumns_set)
    __swig_setmethods__["m_ClampColumns"] = _apogeeUSB.CApnCamera_m_ClampColumns_set
    __swig_getmethods__["m_ClampColumns"] = _apogeeUSB.CApnCamera_m_ClampColumns_get
    if _newclass:m_ClampColumns = _swig_property(_apogeeUSB.CApnCamera_m_ClampColumns_get, _apogeeUSB.CApnCamera_m_ClampColumns_set)
    __swig_setmethods__["m_PreRoiSkipColumns"] = _apogeeUSB.CApnCamera_m_PreRoiSkipColumns_set
    __swig_getmethods__["m_PreRoiSkipColumns"] = _apogeeUSB.CApnCamera_m_PreRoiSkipColumns_get
    if _newclass:m_PreRoiSkipColumns = _swig_property(_apogeeUSB.CApnCamera_m_PreRoiSkipColumns_get, _apogeeUSB.CApnCamera_m_PreRoiSkipColumns_set)
    __swig_setmethods__["m_PostRoiSkipColumns"] = _apogeeUSB.CApnCamera_m_PostRoiSkipColumns_set
    __swig_getmethods__["m_PostRoiSkipColumns"] = _apogeeUSB.CApnCamera_m_PostRoiSkipColumns_get
    if _newclass:m_PostRoiSkipColumns = _swig_property(_apogeeUSB.CApnCamera_m_PostRoiSkipColumns_get, _apogeeUSB.CApnCamera_m_PostRoiSkipColumns_set)
    __swig_setmethods__["m_OverscanColumns"] = _apogeeUSB.CApnCamera_m_OverscanColumns_set
    __swig_getmethods__["m_OverscanColumns"] = _apogeeUSB.CApnCamera_m_OverscanColumns_get
    if _newclass:m_OverscanColumns = _swig_property(_apogeeUSB.CApnCamera_m_OverscanColumns_get, _apogeeUSB.CApnCamera_m_OverscanColumns_set)
    __swig_setmethods__["m_TotalRows"] = _apogeeUSB.CApnCamera_m_TotalRows_set
    __swig_getmethods__["m_TotalRows"] = _apogeeUSB.CApnCamera_m_TotalRows_get
    if _newclass:m_TotalRows = _swig_property(_apogeeUSB.CApnCamera_m_TotalRows_get, _apogeeUSB.CApnCamera_m_TotalRows_set)
    __swig_setmethods__["m_ImagingRows"] = _apogeeUSB.CApnCamera_m_ImagingRows_set
    __swig_getmethods__["m_ImagingRows"] = _apogeeUSB.CApnCamera_m_ImagingRows_get
    if _newclass:m_ImagingRows = _swig_property(_apogeeUSB.CApnCamera_m_ImagingRows_get, _apogeeUSB.CApnCamera_m_ImagingRows_set)
    __swig_setmethods__["m_UnderscanRows"] = _apogeeUSB.CApnCamera_m_UnderscanRows_set
    __swig_getmethods__["m_UnderscanRows"] = _apogeeUSB.CApnCamera_m_UnderscanRows_get
    if _newclass:m_UnderscanRows = _swig_property(_apogeeUSB.CApnCamera_m_UnderscanRows_get, _apogeeUSB.CApnCamera_m_UnderscanRows_set)
    __swig_setmethods__["m_OverscanRows"] = _apogeeUSB.CApnCamera_m_OverscanRows_set
    __swig_getmethods__["m_OverscanRows"] = _apogeeUSB.CApnCamera_m_OverscanRows_get
    if _newclass:m_OverscanRows = _swig_property(_apogeeUSB.CApnCamera_m_OverscanRows_get, _apogeeUSB.CApnCamera_m_OverscanRows_set)
    __swig_setmethods__["m_VFlushBinning"] = _apogeeUSB.CApnCamera_m_VFlushBinning_set
    __swig_getmethods__["m_VFlushBinning"] = _apogeeUSB.CApnCamera_m_VFlushBinning_get
    if _newclass:m_VFlushBinning = _swig_property(_apogeeUSB.CApnCamera_m_VFlushBinning_get, _apogeeUSB.CApnCamera_m_VFlushBinning_set)
    __swig_setmethods__["m_HFlushDisable"] = _apogeeUSB.CApnCamera_m_HFlushDisable_set
    __swig_getmethods__["m_HFlushDisable"] = _apogeeUSB.CApnCamera_m_HFlushDisable_get
    if _newclass:m_HFlushDisable = _swig_property(_apogeeUSB.CApnCamera_m_HFlushDisable_get, _apogeeUSB.CApnCamera_m_HFlushDisable_set)
    __swig_setmethods__["m_ShutterCloseDelay"] = _apogeeUSB.CApnCamera_m_ShutterCloseDelay_set
    __swig_getmethods__["m_ShutterCloseDelay"] = _apogeeUSB.CApnCamera_m_ShutterCloseDelay_get
    if _newclass:m_ShutterCloseDelay = _swig_property(_apogeeUSB.CApnCamera_m_ShutterCloseDelay_get, _apogeeUSB.CApnCamera_m_ShutterCloseDelay_set)
    __swig_setmethods__["m_PixelSizeX"] = _apogeeUSB.CApnCamera_m_PixelSizeX_set
    __swig_getmethods__["m_PixelSizeX"] = _apogeeUSB.CApnCamera_m_PixelSizeX_get
    if _newclass:m_PixelSizeX = _swig_property(_apogeeUSB.CApnCamera_m_PixelSizeX_get, _apogeeUSB.CApnCamera_m_PixelSizeX_set)
    __swig_setmethods__["m_PixelSizeY"] = _apogeeUSB.CApnCamera_m_PixelSizeY_set
    __swig_getmethods__["m_PixelSizeY"] = _apogeeUSB.CApnCamera_m_PixelSizeY_get
    if _newclass:m_PixelSizeY = _swig_property(_apogeeUSB.CApnCamera_m_PixelSizeY_get, _apogeeUSB.CApnCamera_m_PixelSizeY_set)
    __swig_setmethods__["m_Color"] = _apogeeUSB.CApnCamera_m_Color_set
    __swig_getmethods__["m_Color"] = _apogeeUSB.CApnCamera_m_Color_get
    if _newclass:m_Color = _swig_property(_apogeeUSB.CApnCamera_m_Color_get, _apogeeUSB.CApnCamera_m_Color_set)
    __swig_setmethods__["m_MinSuggestedExpTime"] = _apogeeUSB.CApnCamera_m_MinSuggestedExpTime_set
    __swig_getmethods__["m_MinSuggestedExpTime"] = _apogeeUSB.CApnCamera_m_MinSuggestedExpTime_get
    if _newclass:m_MinSuggestedExpTime = _swig_property(_apogeeUSB.CApnCamera_m_MinSuggestedExpTime_get, _apogeeUSB.CApnCamera_m_MinSuggestedExpTime_set)
    __swig_setmethods__["m_TempRampRateOne"] = _apogeeUSB.CApnCamera_m_TempRampRateOne_set
    __swig_getmethods__["m_TempRampRateOne"] = _apogeeUSB.CApnCamera_m_TempRampRateOne_get
    if _newclass:m_TempRampRateOne = _swig_property(_apogeeUSB.CApnCamera_m_TempRampRateOne_get, _apogeeUSB.CApnCamera_m_TempRampRateOne_set)
    __swig_setmethods__["m_TempRampRateTwo"] = _apogeeUSB.CApnCamera_m_TempRampRateTwo_set
    __swig_getmethods__["m_TempRampRateTwo"] = _apogeeUSB.CApnCamera_m_TempRampRateTwo_get
    if _newclass:m_TempRampRateTwo = _swig_property(_apogeeUSB.CApnCamera_m_TempRampRateTwo_get, _apogeeUSB.CApnCamera_m_TempRampRateTwo_set)
    __swig_setmethods__["m_PlatformTempSetpointSlope"] = _apogeeUSB.CApnCamera_m_PlatformTempSetpointSlope_set
    __swig_getmethods__["m_PlatformTempSetpointSlope"] = _apogeeUSB.CApnCamera_m_PlatformTempSetpointSlope_get
    if _newclass:m_PlatformTempSetpointSlope = _swig_property(_apogeeUSB.CApnCamera_m_PlatformTempSetpointSlope_get, _apogeeUSB.CApnCamera_m_PlatformTempSetpointSlope_set)
    __swig_setmethods__["m_PlatformTempSetpointIntercept"] = _apogeeUSB.CApnCamera_m_PlatformTempSetpointIntercept_set
    __swig_getmethods__["m_PlatformTempSetpointIntercept"] = _apogeeUSB.CApnCamera_m_PlatformTempSetpointIntercept_get
    if _newclass:m_PlatformTempSetpointIntercept = _swig_property(_apogeeUSB.CApnCamera_m_PlatformTempSetpointIntercept_get, _apogeeUSB.CApnCamera_m_PlatformTempSetpointIntercept_set)
    __swig_setmethods__["m_PlatformTempBackoffMin"] = _apogeeUSB.CApnCamera_m_PlatformTempBackoffMin_set
    __swig_getmethods__["m_PlatformTempBackoffMin"] = _apogeeUSB.CApnCamera_m_PlatformTempBackoffMin_get
    if _newclass:m_PlatformTempBackoffMin = _swig_property(_apogeeUSB.CApnCamera_m_PlatformTempBackoffMin_get, _apogeeUSB.CApnCamera_m_PlatformTempBackoffMin_set)
    __swig_setmethods__["m_PlatformTempBackoffMax"] = _apogeeUSB.CApnCamera_m_PlatformTempBackoffMax_set
    __swig_getmethods__["m_PlatformTempBackoffMax"] = _apogeeUSB.CApnCamera_m_PlatformTempBackoffMax_get
    if _newclass:m_PlatformTempBackoffMax = _swig_property(_apogeeUSB.CApnCamera_m_PlatformTempBackoffMax_get, _apogeeUSB.CApnCamera_m_PlatformTempBackoffMax_set)
    def FillImageBuffer(self, *args): return _apogeeUSB.CApnCamera_FillImageBuffer(self, *args)
CApnCamera_swigregister = _apogeeUSB.CApnCamera_swigregister
CApnCamera_swigregister(CApnCamera)

# This file is compatible with both classic and new-style classes.


